local _, BeavisQoL = ...

BeavisQoL = BeavisQoL or {}
BeavisQoL.Localization = BeavisQoL.Localization or {}

BeavisQoL.Localization.deDE = {
	-- Allgemein
	UNKNOWN = "Unbekannt",
	RELOAD = "Neu laden",
	CLOSE = "Schließen",
	CANCEL = "Abbrechen",
	VERSION = "Version",
	LANGUAGE = "Sprache",

	-- Header/Main
	HEADER_SUBTITLE = "QoL-Hub für Fortschritt, Komfort und Interface",

	-- Navigation
	NAVIGATION = "Navigation",
	NAVIGATION_HINT = "",
	NAVIGATION_SEARCH_PLACEHOLDER = "Navigation durchsuchen",
	NAVIGATION_SEARCH_HINT = "Filtert Namen und Seitentexte live.",
	NAVIGATION_SEARCH_RESULTS = "%d Treffer in der Navigation",
	NAVIGATION_SEARCH_EMPTY = "Keine Treffer in der Navigation.",
	GENERAL = "Allgemein",
	MODULES = "Module",
	HOME = "Startseite",
	SETTINGS = "Einstellungen",
	PROGRESS = "Fortschritt",
	GOLD_TRADE = "Gold & Handel",
	COMFORT = "Komfort",
	INTERFACE_COMBAT = "Interface & Kampf",
	GROUP_SEARCH = "Gruppe & Suche",
	STREAMER_TOOLS = "Streamer Tools",
	COMPANION = "Begleiter",

	-- Module/Entries
	LEVEL_TIME = "Levelzeit",
	CHECKLIST = "Checkliste",
	WEEKLY_KEYS = "Weekly Keys",
	ITEMLEVEL_GUIDE = "Itemlevel Guide",
	QUEST_CHECK = "Quest Check",
	QUEST_ABANDON = "Quest-Abbruch",
	LOGGING = "Logging",
	AUTOSELL_JUNK = "Auto Sell Junk",
	AUTOREPAIR = "Auto Repair",
	FAST_LOOT = "Fast Loot",
	EASY_DELETE = "Easy Delete",
	TOOLTIP_ITEMLEVEL = "Tooltip-Itemlevel",
	CAMERA_DISTANCE = "Kameraweite",
	PREY_HUNT_PROGRESS = "Jagd-Fortschritt",
	FISHING_HELPER = "Angelhilfe",
	STATS = "Stats",
	MARKER_BAR = "Markerleiste",
	COMBAT_TEXT = "Combat Text",
	MOUSE_HELPER = "Maus-Helfer",
	BOSS_GUIDES = "Boss Guides",
	LFG = "Gruppensuche",
	STREAMER_PLANNER = "Gruppenplaner",
	PET_STUFF = "Pet Stuff",

	-- Settings
	GLOBAL_SETTINGS = "Globale Addon-Einstellungen",
	GLOBAL_SETTINGS_DESC = "Hier kannst du Einstellungen für das gesamte Addon-Fenster und den Minimap-Button anpassen.",
	SETTINGS_SECTION_GENERAL = "Allgemein",
	SETTINGS_SECTION_GENERAL_DESC = "Sprache und Verhalten des Hauptfensters gehören zusammen und stehen deshalb ganz oben.",
	SETTINGS_SECTION_MINIMAP = "Minimap",
	SETTINGS_SECTION_MINIMAP_DESC = "Optionen für das Symbol an der Minimap bleiben in einem eigenen Block getrennt vom Rest der Oberfläche.",
	SETTINGS_SECTION_QUICK_HIDE = "Schnell ausblenden",
	SETTINGS_SECTION_QUICK_HIDE_DESC = "Hier legst du fest, welche Overlays in instanzierten Bereichen automatisch ausgeblendet werden und ob das nur im Kampf passieren soll.",
	SETTINGS_SECTION_RESET = "Zurücksetzen",
	SETTINGS_SECTION_RESET_DESC = "Seltene Notfall- oder Korrekturaktionen stehen separat, damit sie nicht zwischen normalen Optionen untergehen.",
	LOCK_WINDOW = "Hauptfenster fixieren (nicht verschiebbar)",
	MINIMAP_BUTTON_HIDE = "Minimap-Button ausblenden",
	QUICK_HIDE_OVERLAYS = "Overlays schnell ausblenden",
	QUICK_HIDE_CHECKLIST_OVERLAY = "Checklisten-Overlay ausblenden",
	QUICK_HIDE_WEEKLY_OVERLAY = "Weekly-Overlay ausblenden",
	QUICK_HIDE_STATS_OVERLAY = "Stats-Overlay ausblenden",
	QUICK_HIDE_OVERLAYS_IN_COMBAT = "Nur im Kampf ausblenden",
	HIDE_OVERLAYS_IN_COMBAT = "Overlays in Instanzen im Kampf ausblenden",
	RESET_POSITION = "Position zurücksetzen",

	-- Home/Startseite
	WELCOME_TITLE = "Willkommen bei %s",
	WELCOME_SUBTITLE = "Zentrale Übersicht für Fortschritt, Komfort und Interface",
	WELCOME_BODY = "Beavis Quality of Life bündelt wichtige Alltagsfunktionen in einer Oberfläche: Tracker, Weekly-Ansichten, Komfortmodule und UI-Werkzeuge.",
	PROJECT_STATUS = "Projektstatus",
	RELEASE_STATUS_FORMAT = "Status: %s",
	RELEASE_CHANNEL_ALPHA = "Alpha",
	RELEASE_CHANNEL_BETA = "Beta",
	RELEASE_CHANNEL_RC = "Release Candidate",
	RELEASE_CHANNEL_RELEASE = "Release",
	STATUS_ALPHA = "Status: Alpha, aktiv im Ausbau",
	STATUS_FOCUS = "Fokus: stabile Kernmodule, klare Bedienung und ein kompakter Zugriff auf häufig genutzte Funktionen.",

	PROGRESS_CARD_TITLE = "Fortschritt im Blick",
	PROGRESS_CARD_BODY = "Levelzeit, Checkliste, Weekly Keys, Itemlevel Guide und Quest Check holen die Dinge nach vorne, die man sonst über mehrere Blizzard-Fenster verteilt suchen muss.",
	PROGRESS_CARD_FOOTER = "Levelzeit - Checkliste - Weekly Keys - Itemlevel Guide - Quest Check",

	COMFORT_CARD_TITLE = "Weniger Kleinkram",
	COMFORT_CARD_BODY = "Komfort-Module decken typische Routineaufgaben ab, darunter Looten, Reparieren, Verkaufen und kleine UI-Erweiterungen für den Alltag.",
	COMFORT_CARD_FOOTER = "Auto Sell - Auto Repair - Fast Loot - Easy Delete - Kameraweite",

	TWITCH_TITLE = "Twitch",
	TWITCH_BODY = "Wenn du sehen willst, wie das Addon weiter wächst, findest du Streams, Updates und den direkten Draht auf twitch.tv/beavismania.",
	TWITCH_FOOTER = "Zum Twitch-Kanal",
	TWITCH_POPUP = "Twitch-Kanal öffnen",

	DISCORD_TITLE = "Discord & Support",
	DISCORD_BODY = "Feedback, Ideen und Support laufen über die Website und die Community-Kanäle. So lassen sich Rückmeldungen und offene Punkte gesammelt nachhalten.",
	DISCORD_FOOTER = "Zur Beavismania-Website",
	DISCORD_POPUP = "Beavismania öffnen",

	FOOTER_TEXT = "Die Oberfläche ist auf kurze Wege, klare Bereiche und ausreichend Platz für zusätzliche Module ausgelegt.",

	-- Link-Popup
	LINK_OPEN = "Link öffnen",
	LINK_COPY_DESC = "World of Warcraft erlaubt Addons nicht, Webseiten direkt zu öffnen. Du kannst die Adresse hier markieren und kopieren:",
	LINK_COPY_HINT = "Tipp: Link markieren und mit Strg+C kopieren.",
	MINIMAP_TRACKER_SHOW = "Checklisten-Tracker anzeigen",
	MINIMAP_WEEKLY_KEYS_SHOW = "Weekly Keys anzeigen",
	MINIMAP_STATS_SHOW = "Stats anzeigen",
	MINIMAP_MARKER_BAR_SHOW = "Markerleiste anzeigen",
	MINIMAP_STREAMER_PLANNER_SHOW = "Gruppenplaner anzeigen",
	MINIMAP_EASY_LFG_SHOW = "Easy LFG anzeigen",
	MINIMAP_PORTAL_VIEWER_SHOW = "Portal Viewer anzeigen",
	MINIMAP_LEFT_CLICK = "Linksklick: Fenster öffnen / schließen",
	MINIMAP_RIGHT_CLICK = "Rechtsklick: Schnellmenü",
	MINIMAP_SHIFT_CLICK = "Shift-Klick: UI neu laden",
	MINIMAP_DRAG = "Drag: Position ändern",
	ACTIVE = "Aktiv",
	FONT = "Schriftart",
	DISPLAY = "Darstellung",
	IMPORTANT = "Wichtig",
	READY = "Bereit",
	NOT_FOUND = "Nicht gefunden",
	STATUS = "Status",
	ADDON_MESSAGE = "Beavis QoL: %s",
	PORTAL_VIEWER_TITLE = "Portal Viewer",
	PORTAL_VIEWER_SUBTITLE = "Midnight S1 Dungeonportale",
	PORTAL_VIEWER_HINT = "Zeigt dir für die aktuelle Mythic+-Rotation von Midnight Saison 1, welche Dungeonportale du schon hast und welche noch fehlen.",
	PORTAL_VIEWER_SECTION_AVAILABLE = "Vorhanden",
	PORTAL_VIEWER_SECTION_MISSING = "Fehlt",
	PORTAL_VIEWER_EMPTY_AVAILABLE = "Noch kein Saison-1-Portal freigeschaltet.",
	PORTAL_VIEWER_EMPTY_MISSING = "Alle Saison-1-Portale sind vorhanden.",
	PORTAL_VIEWER_UNLOCKED = "Freigeschaltet",
	PORTAL_VIEWER_LOCKED = "Nicht freigeschaltet",
	PORTAL_VIEWER_ACTION_USE = "Porten",
	PORTAL_VIEWER_ACTION_MISSING = "Fehlt",
	PORTAL_VIEWER_CLICK_HINT = "Linksklick: Portal benutzen",
	PORTAL_VIEWER_ACHIEVEMENT_UNKNOWN = "Kein passender Portal-Erfolg gefunden",
	PORTAL_VIEWER_REQUIREMENT = "Freischaltung: Portal-Belohnung für diesen Dungeon",
	PORTAL_VIEWER_CLOSE_TOOLTIP = "Fenster ausblenden",
	PORTAL_VIEWER_DUNGEON_MAGISTERS_TERRACE = "Terrasse der Magister",
	PORTAL_VIEWER_DUNGEON_MAISARA_CAVERNS = "Maisarakavernen",
	PORTAL_VIEWER_DUNGEON_NEXUS_POINT_XENAS = "Nexuspunkt Xenas",
	PORTAL_VIEWER_DUNGEON_WINDRUNNER_SPIRE = "Windläuferturm",
	PORTAL_VIEWER_DUNGEON_ALGETHAR_ACADEMY = "Akademie von Algeth'ar",
	PORTAL_VIEWER_DUNGEON_PIT_OF_SARON = "Die Grube von Saron",
	PORTAL_VIEWER_DUNGEON_SEAT_OF_THE_TRIUMVIRATE = "Sitz des Triumvirats",
	PORTAL_VIEWER_DUNGEON_SKYREACH = "Himmelsnadel",

	MISC_TITLE = "Komfort",
	MISC_DESC = "Hier findest du Komfortfunktionen, die unabhängig vom Rest des Addons genutzt werden können.",
	AUTOSELL_HINT = "Verkauft beim Öffnen eines Händlers automatisch alle grauen Gegenstände mit Händlerwert.",
	AUTOREPAIR_HINT = "Repariert beim Öffnen eines Händlers automatisch beschädigte Gegenstände.",
	AUTOREPAIR_GUILD = "Per Gilde vorrangig",
	AUTOREPAIR_GUILD_HINT = "Wenn möglich, wird zuerst Gildengold für die Reparatur verwendet.",
	EASY_DELETE_HINT = "Entfernt bei Items mit LÖSCHEN-Abfrage die Texteingabe und ersetzt sie durch eine einfache Bestätigung.",
	FAST_LOOT_HINT = "Lootet Beute direkt beim Öffnen und blendet das Lootfenster dabei aus.",
	CUTSCENE_SKIP = "Cutscene Skip",
	CUTSCENE_SKIP_HINT = "Zeigt Cutscenes und Movies beim ersten Ausloesen normal an. Sobald derselbe Event-Schluessel bereits einmal gesehen wurde, wird er beim naechsten Start automatisch uebersprungen.",
	FLIGHT_MASTER_TIMER = "Flugmeister-Timer",
	FLIGHT_MASTER_TIMER_HINT = "Zeigt während Flugmeister-Flügen mittig am Bildschirm einen Countdown bis zur Ankunft an und lernt fehlende Routenzeiten automatisch nach.",
	FLIGHT_MASTER_TIMER_UNKNOWN = "Ankunft unbekannt",
	FLIGHT_MASTER_TIMER_SOUND = "Ankunftssound aktiv",
	FLIGHT_MASTER_TIMER_SOUND_HINT = "Spielt bei der Ankunft einmal ein kurzes Signal ab. Die Auswahl nutzt Blizzard-Client-Sounds; es werden keine fremden Audiodateien mitgeliefert.",
	FLIGHT_MASTER_TIMER_SOUND_SELECT = "Sound:",
	FLIGHT_MASTER_TIMER_SOUND_TEST = "Test",
	FLIGHT_MASTER_TIMER_SOUND_PLAY_HINT = "Spielt den aktuell gewählten Sound einmal ab.",
	FLIGHT_MASTER_TIMER_SOUND_SQUIRE_HORN = "Knappenhorn",
	FLIGHT_MASTER_TIMER_SOUND_DWARF_HORN = "Zwergenhorn",
	FLIGHT_MASTER_TIMER_SOUND_SIMON_CHIME = "Simon-Klang",
	FLIGHT_MASTER_TIMER_SOUND_SCOURGE_HORN = "Geißelhorn",
	FLIGHT_MASTER_TIMER_SOUND_GRIMRAIL_TRAIN_HORN = "Grimmgleis-Zughorn",
	FLIGHT_MASTER_TIMER_LOCK_OVERLAY = "Timer fixieren",
	FLIGHT_MASTER_TIMER_LOCK_OVERLAY_HINT = "Wenn gelöst, kannst du das Timer-Overlay während eines Flugs direkt mit Linksklick verschieben. Standardmäßig bleibt es fixiert.",
	FLIGHT_MASTER_TIMER_POSITION_MODE = "Positionieren",
	FLIGHT_MASTER_TIMER_POSITION_MODE_STOP = "Positionieren beenden",
	FLIGHT_MASTER_TIMER_POSITION_MODE_HINT = "Blendet ein Beispiel-Overlay ein, damit du die Position auch ohne aktiven Flug verschieben und danach direkt wieder fixieren kannst.",
	FLIGHT_MASTER_TIMER_PREVIEW_DESTINATION = "Dornogal",
	FLIGHT_MASTER_TIMER_RESET_HINT = "Setzt das Timer-Overlay auf seine Standardposition unterhalb der Bildschirmmitte zurück.",
	TOOLTIP_ITEMLEVEL_HINT = "Zeigt im Mouseover-Tooltip das ausgerüstete Itemlevel anderer Spieler an. Funktioniert per Inspect nur in Reichweite.",
	TOOLTIP_ITEMLEVEL_LABEL = "Itemlevel",
	TOOLTIP_ITEMLEVEL_LOADING = "wird geprüft...",
	PREY_HUNT_PROGRESS_HINT = "Blendet bei einer aktiven Midnight-Jagd die aktuelle Stufe direkt am Blizzard-Jagd-Symbol ein.",
	PREY_HUNT_STAGE_FORMAT = "Phase %d/%d",
	PREY_HUNT_STAGE_READY = "Boss bereit",
	KEYSTONE_ACTIONS = "Schlüsselstein-Buttons",
	KEYSTONE_ACTIONS_HINT = "Ersetzt im Mythic+-Schlüsselsteinfenster den Aktivieren-Button durch Readycheck und Timer & GO. Mit Auto Timer startet Timer & GO automatisch, sobald nach deinem Readycheck alle bereit sind; abbrechen kannst du weiter über den Knopf.",
	KEYSTONE_ACTIONS_GROUP_LOCK = "Knöpfe nur in Gruppe aktiv",
	KEYSTONE_ACTIONS_GROUP_LOCK_HINT = "Wenn aktiv, bleiben Readycheck und Timer & GO außerhalb einer Gruppe gesperrt.",
	KEYSTONE_ACTIONS_SECONDS = "Timer-Sekunden:",
	KEYSTONE_ACTIONS_SECONDS_HINT = "Gilt für Timer & GO und Auto Timer. Zulässig sind 1 bis 30 Sekunden.",
	KEYSTONE_ACTIONS_AUTOTIMER = "Auto Timer",
	KEYSTONE_ACTIONS_READYCHECK = "Readycheck",
	KEYSTONE_ACTIONS_PULLTIMER = "Timer & GO",
	KEYSTONE_ACTIONS_CANCEL = "Abbrechen",
	FISHING_HELPER_DESC = "Ein Ein-Tasten-Modul für entspanntes Angeln. Dieselbe Taste wirft die Angel aus und wird solange dein Bobber aktiv ist vorübergehend auf Blizzards Interaktion umgelegt, damit du ihn ohne exakten Mouseover mit derselben Taste einsammeln kannst.",
	FISHING_HELPER_USAGE_HINT = "Ablauf: Taste drücken zum Auswerfen, dann den Bobber im Blick behalten und dieselbe Taste erneut drücken. Während der Bobber im Wasser ist, bleibt deine Taste auf Interaktion gelegt statt erneut auszuwerfen.",
	FISHING_HELPER_ENABLE = "Angelhilfe aktivieren",
	FISHING_HELPER_SET_KEY = "Taste festlegen",
	FISHING_HELPER_CLEAR_KEY = "Taste löschen",
	FISHING_HELPER_CURRENT_KEY = "Aktuelle Taste",
	FISHING_HELPER_NO_KEY = "Keine Taste festgelegt",
	FISHING_HELPER_CAPTURE_HINT = "Drücke jetzt die gewünschte Taste. Escape bricht ab, Entfernen löscht die Belegung.",
	FISHING_HELPER_STATUS = "Status",
	FISHING_HELPER_STATUS_DISABLED = "Deaktiviert",
	FISHING_HELPER_STATUS_IDLE = "Bereit zum Auswerfen",
	FISHING_HELPER_STATUS_WAITING = "Pose im Wasser - warte auf Biss",
	FISHING_HELPER_STATUS_READY = "Biss erkannt - Interaktion liegt auf deiner Taste",
	FISHING_HELPER_STATUS_NO_SPELL = "Angeln nicht gefunden",
	FISHING_HELPER_STATUS_CAPTURE = "Warte auf Tasteneingabe",
	FISHING_HELPER_INTERACT_BINDING = "Blizzard-Interaktion",
	FISHING_HELPER_INTERACT_BINDING_NONE = "Keine Standardtaste belegt",
	FISHING_HELPER_INTERACT_HINT = "Sobald der Bobber aktiv ist, wird deine festgelegte Taste vorübergehend auf Blizzards Interaktion umgebogen. Zusätzlich setzt das Modul Soft-Interact währenddessen kurz auf den passenden Wert, damit richtungsbasiertes Einsammeln greift.",
	FISHING_HELPER_SOUND_ENABLE = "Angel-Sound hervorheben",
	FISHING_HELPER_SOUND_MIN = "Angel-Sound-Verstärkung",
	FISHING_HELPER_SOUND_HINT = "Solange deine Pose im Wasser ist, dämpft das Addon Musik, Ambiente und Haustier-Sounds, hebt Effekt- und Masterlautstärke relativ zu deinem aktuellen Mix an und stellt danach alles wieder her. 100% = unverändert, 200% = doppelt so laut bis zum WoW-Limit.",
	MOUSE_HELPER_DESC = "Bündelt Maus-Qualitätseinstellungen in einer Seite: sichtbarer Marker um den Cursor, ein bewegter Trail und die Blizzard-Mausvergrößerung.",
	MOUSE_HELPER_SETTINGS = "Allgemein",
	MOUSE_HELPER_ENABLE = "Maus-Helfer aktivieren",
	MOUSE_HELPER_CURSOR_SIZE = "Blizzard-Mausgröße",
	MOUSE_HELPER_CURSOR_SIZE_DEFAULT = "Standard",
	MOUSE_HELPER_CURSOR_SIZE_32 = "32x32",
	MOUSE_HELPER_CURSOR_SIZE_48 = "48x48",
	MOUSE_HELPER_CURSOR_SIZE_64 = "64x64",
	MOUSE_HELPER_CURSOR_SIZE_96 = "96x96",
	MOUSE_HELPER_CURSOR_SIZE_128 = "128x128",
	MOUSE_HELPER_BLIZZARD_CURSOR = "Blizzard-Maus vergrößern",
	MOUSE_HELPER_BLIZZARD_CURSOR_HINT = "Schaltet die eingebaute Blizzard-Funktion für einen größeren Mauszeiger direkt hier mit.",
	MOUSE_HELPER_BLIZZARD_CURSOR_UNSUPPORTED = "Auf diesem Client konnte keine unterstützte Blizzard-CVar für Mausgrößen erkannt werden.",
	MOUSE_HELPER_CIRCLE_TITLE = "Cursor-Kreis",
	MOUSE_HELPER_CIRCLE_ENABLE = "Kreis anzeigen",
	MOUSE_HELPER_CIRCLE_COMBAT_ONLY = "Kreis nur im Kampf anzeigen",
	MOUSE_HELPER_CIRCLE_SIZE = "Größe",
	MOUSE_HELPER_CIRCLE_THICKNESS = "Rahmenstärke",
	MOUSE_HELPER_CIRCLE_SHAPE = "Form",
	MOUSE_HELPER_SHAPE_RING = "Ring",
	MOUSE_HELPER_SHAPE_SQUARE = "Quadrat",
	MOUSE_HELPER_SHAPE_DIAMOND = "Raute",
	MOUSE_HELPER_COLOR_PICK = "Farbe wählen",
	MOUSE_HELPER_CIRCLE_HINT = "Der Kreis folgt deiner Maus in Echtzeit und bleibt mittig um den Cursor.",
	MOUSE_HELPER_TRAIL_TITLE = "Maus-Trail",
	MOUSE_HELPER_TRAIL_ENABLE = "Trail anzeigen",
	MOUSE_HELPER_TRAIL_LENGTH = "Länge",
	MOUSE_HELPER_TRAIL_SIZE = "Punktgröße",
	MOUSE_HELPER_TRAIL_STYLE = "Trail-Stil",
	MOUSE_HELPER_TRAIL_STYLE_LIGHTNING = "Blitz",
	MOUSE_HELPER_TRAIL_STYLE_HOLY = "Heiliges Licht",
	MOUSE_HELPER_TRAIL_STYLE_ARC = "Bögen (Ice)",
	MOUSE_HELPER_TRAIL_STYLE_CLEAN = "Sauber",
	MOUSE_HELPER_TRAIL_HINT = "Der Trail hinterlässt beim Bewegen kurze Punkte, die nach hinten sanft ausblenden.",
	BOSS_GUIDES_DESC = "Zeigt in unterstützten Dungeons/Raids oben links einen Boss-Guides-Button. Darüber öffnest du ein Fenster mit Boss-Tabs und den hinterlegten Taktiken.",
	BOSS_GUIDES_SETTINGS = "Einstellungen",
	BOSS_GUIDES_SHOW_OVERLAY = "Overlay-Button anzeigen",
	BOSS_GUIDES_OVERLAY_MODE = "Anzeigemodus",
	BOSS_GUIDES_MODE_ALWAYS = "Immer anzeigen",
	BOSS_GUIDES_MODE_INSTANCE = "Nur in Dungeon/Raid",
	BOSS_GUIDES_LOCK_OVERLAY = "Overlay-Position fixieren",
	BOSS_GUIDES_SCALE = "Skalierung",
	BOSS_GUIDES_FONT_SIZE = "Schriftgröße",
	BOSS_GUIDES_RESET_POSITION = "Positionen zurücksetzen",
	BOSS_GUIDES_BUTTON = "Boss Guides",
	BOSS_GUIDES_BOSSES = "Bosse",
	BOSS_GUIDES_INSTANCE = "Instanz",
	BOSS_GUIDES_NO_GUIDE = "Für diese Instanz ist aktuell kein Guide hinterlegt.",
	BOSS_GUIDES_CURRENT_INSTANCE = "Aktuelle Instanz",
	BOSS_GUIDES_NONE = "Keine",
	BOSS_GUIDES_CAT_RAID = "Raid",
	BOSS_GUIDES_CAT_DUNGEON = "Dungeon",
	BOSS_GUIDES_SELECT_INSTANCE = "Instanz wählen...",
	BOSS_GUIDES_NO_INSTANCES = "Noch keine Einträge",
	BOSS_GUIDES_SECTION_GENERAL = "Allgemein",
	BOSS_GUIDES_LABEL_MYTHIC = "Mythisch",
	BOSS_GUIDES_LEGEND_TANK = "Tank",
	BOSS_GUIDES_LEGEND_DD = "DD",
	BOSS_GUIDES_LEGEND_HEAL = "Heal",
	BOSS_GUIDES_LEGEND_HC = "HC",
	BOSS_GUIDES_LEGEND_M = "M",
	BOSS_GUIDES_INSTANCE_VOIDSPIRE_TITLE = "Leerenspitze",
	BOSS_GUIDES_INSTANCE_VOIDSPIRE_TOKENS = { "leerenspitze", "leeren", "voidspire", "void spire" },
	BOSS_GUIDES_BOSS_IMPERATOR_AVERZIAN_NAME = "Imperator Averzian",
	BOSS_GUIDES_BOSS_IMPERATOR_AVERZIAN_BODY = [=[
Allgemein: Tic Tac Toe spielen. Schattenphalanx überrennt zwischendurch einzelne Linien - Ausweichen!. Drei verlorene Felder in einer Reihe lösen Marsch der Unendlichen aus und wipen das Feld.
{TANK} Boss nie auf beanspruchte Felder vom Leerenportal stellen. Bei ca 10 Stapeln Schwärzende Wunden tauschen. Add-Wellen übernimmt der freie Tank.
{DD} Umbralkollaps mit der ganzen Gruppe beim Tank soaken. Adds haben Priorität.
{HEAL} Umbralkollaps und Dunkle Verwerfung gegenheilen.
{HC} Leerenformer sofort fokussen. Bollwerk errichten kicken. Aufziehende Dunkelheit nie durchlassen, sonst steht ein zusätzlicher Obskurionendwandler. Leerenschlund bei 35% hard focussen: Dunkle Resilienz ist nicht kickbar - also stunnen und töten - bevor er das Feld erreicht und sich heilt.
{M} Schwarzes Miasma priorisiert dispellen. Kosmischer Panzer vor Umbralkollaps entfernen. Leerenmarkiert sauber rausziehen.
]=],
	BOSS_GUIDES_BOSS_VORASIUS_NAME = "Vorasius",
	BOSS_GUIDES_BOSS_VORASIUS_BODY = [=[
Allgemein: Leerenatem spawnt links oder rechts und zieht von dort über die Plattform. Der ganze Raid muss ausweichen.
{TANK} Immer in Nahkampfreichweite bleiben, sonst Überwältigender Puls den Raid trifft. Tanks soaken Schattenklauenhieb 2x alleine im Wechsel. Zwei Flächen soaken - tauschen - wiederholen.
{DD} Blasenkriecher verfolgen Spieler. Spieler teilen sie auf beide Wände auf. Das Platzen zerstört die Wände. Danach Leerenatem ausweichen.
{HEAL} CDs für Pustelbersten und Urzeitliches Brüllen einplanen.
{HC} Wände brauchen mehr Explosionen. Add-Kills vorher ansagen und Platz sparen.
{M} Pustelbersten hinterlässt Dunklen Schleim. Kill-Zonen strikt planen und Wege nicht doppelt blocken.
]=],
	BOSS_GUIDES_BOSS_FALLEN_KING_SALHADAAR_NAME = "Gefallener König Salhadaar",
	BOSS_GUIDES_BOSS_FALLEN_KING_SALHADAAR_BODY = [=[
Allgemein: Kugeln dürfen den Boss nicht erreichen. Jede Kugel erhöht den Raidschaden stark.
{TANK} Boss von Kugeln & Quälender Extrakt wegziehen. Bei Destabilisierende Schläge tauschen.
{DD} Kugel vor Bosskontakt zerstören. Abbilder sofort kicken. Entropische Entfesselung ist euer Burn-Fenster (25% mehr DMG am Boss). Mit Zertrümmerndes Zwielicht an den Rand stellen und Fläche ablegen.
{HEAL} Leereninfusion, Windende Obskurität und Entropische Entfesselung mit CDs decken. Erdrückende Dunkelheit gezielt dispellen. Mit Zertrümmerndes Zwielicht an den Rand stellen und Fläche ablegen.
{HC} Kugeln platzen und wirken Dunkle Strahlung mit Raidweiten Schaden. Zertrümmerndes Zwielicht springt bei Einschlag auf freundliche Ziele über.
{M} Kügeln hinterlassen Beständige Leere. Nexusschild auf Abbildern per Kick-Rotation runterspielen.
]=],
	BOSS_GUIDES_BOSS_VAELGOR_EZZORAK_NAME = "Vaelgor & Ezzorak",
	BOSS_GUIDES_BOSS_VAELGOR_EZZORAK_BODY = [=[
Allgemein: Zwei Bosse. HP angleichen und 15 Meter Abstand halten, sonst Zwielichtband. Nie hinter den Drachen stehen. Ablauf immer gleich: Leerenheulen -> Nullstrahl/Nullzone -> Düsterkeit. Markierter Spieler zieht Entsetzlicher Atem raus und wird danach sofort dispellt. Leerenkugeln zusammenziehen, stoppen und töten. Zwischenphase: in die Strahlende Barriere, Kreise raus, Add sofort töten.
{TANK} Drachen an den Spawnpunkten getrennt halten. Nullstrahl frontal weg vom Raid. Nach jeder Düsterkeit oder spätestens nach Vaelflügel/Rakzahn tauschen. Bosse nicht unnötig durch den Raum ziehen.
{DD} Bei Leerenheulen eng stacken, damit die Leerenkugeln zusammen spawnen. Nullzone sofort lösen; der Tank löst zuletzt. Düsterkeit mit fester Soak-Gruppe auf Marker spielen. Rest weicht Atem, Kugeln und Pfützen aus.
{HEAL} CDs für Nullzonen-Explosion, Düsterkeit und Mitternachtsflammen einteilen. Fear von Entsetzlicher Atem sofort dispellen. Kreisziele in der Zwischenphase stabil halten.
{HC} Nach kompletter Nullzone nimmt der Raid extra Schaden. Düsterkeit-Soaker bekommen eine Soak-Vulnerabilität und können nicht direkt wieder soaken.
{M} Beim ersten gelösten Nullzone-Band spawnen Bodenkreise. Langsame Klassen können kurz in Nullstrahl gehen, um leichter rauszukommen. Düsterkeit cleaved um Soaker herum und verteilt Düsternisberührt -> Geschwächt. Kosmose-Klone kopieren Bossmechaniken. Ungebundener Schatten in der Zwischenphase sofort fokussieren.
]=],

	BOSS_GUIDES_BOSS_LIGHTBLINDED_VANGUARD_NAME = "Lichtblinde Vorhut",
	BOSS_GUIDES_BOSS_LIGHTBLINDED_VANGUARD_BODY = [=[
Allgemein: Drei Bosse. HP angleichen und keinen zu früh töten, sonst Vergeltung. Bellamy und Senn sind auf Pull kurz immun; Startziel ist Venel. Der Boss mit der nächsten Aura muss an den Rand. Reihenfolge der Auren: Bellamy -> Venel -> Senn. Nach jeder Aura bleibt Weihe liegen und das Feld wird kleiner.
{TANK} Venel: Richturteil -> Finales Urteil sofort tauschen. Bellamy: Richturteil -> Schild der Rechtschaffenen sofort tauschen. Senns Exorzismus defensiv nehmen. Immer den Boss mit kommender Aura an den Rand setzen.
{DD} In Aura der Hingabe und Aura des Friedens keine falschen Ziele cleaven. Todesurteil mit festen Soak-Gruppen spielen; Kreise nie stacken. Danach Göttliche Hämmer und Elekkansturm dodgen. Heiliges Schild sofort brechen, dann Blendendes Licht kicken. Schild des Rächers spreaden und Göttliches Läuten ausweichen.
{HEAL} Lichtinfundiert tickt permanent und wird mit jeder Aura schlimmer. CDs für Göttliches Läuten, Heiliges Läuten, Sengende Strahlkraft und Todesurteil einteilen. Tyrs Zorn auf die 3 Nächsten rotieren lassen und früh gegenheilen.
{HC} Weihe bleibt dauerhaft liegen. Bosse sauber am Rand rotieren, sonst geht euch der Platz aus.
{M} Eifergeist verstärkt immer einen Boss. Bellamy: Tyrs Zorn mit Göttlichem Läuten und Schild des Rächers auf alle Spieler. Venel: Heiliges Läuten mit Todesurteil und Lichttornados bei Göttlicher Sturm. Senn: Todesurteil mit Tyrs Zorn und Sengende Strahlkraft rampt hoch. Mythische Weihe pacified und erhöht erlittenen Schaden.
]=],

	BOSS_GUIDES_BOSS_CROWN_OF_COSMOS_NAME = "Krone des Kosmos",
	BOSS_GUIDES_BOSS_CROWN_OF_COSMOS_BODY = [=[
Allgemein: 3 Phasen, 2 Zwischenphasen. Pfeile sind die Kernmechanik: Sie reinigen Leereffekte, resetten Sternenemission und machen Adds/Wächter überhaupt erst killbar. P1: Wächter früh mit Silberschlag-Pfeilen treffen, damit Verderbende Essenz stapelt; denselben Wächter nicht unnötig nochmal treffen, sonst reset. Leerenausstoß außen legen. Griff der Leere weg vom Raid ziehen. Nullkorona meist nur heilen. Zwischenphasen: in der eigenen Scheibe bleiben, früh von Pfeilen treffen lassen, Debuff abfallen lassen, dann erst wieder treffen lassen; Singularitätsausbruch dodgen. In ZP2 wegen Orbiting Matter sauber durchrotieren. P2: Alleria und Riss-Simulakrum teilen HP. Simulakrum von Boss und Adds fern halten, sonst Verstärkende Dunkelheit stapelt. Kosmische Barriere sofort brechen. Jägerhauptmannszeichen muss Leerenbrut treffen, sonst stirbt sie nicht. Leerenfeuerstoß kicken. P3: Stacken, Aspekt des Endes in der Reihenfolge Fernkampf -> Nahkampf -> Tank brechen. Griff der Leere gemeinsam legen. Bei Verschlingender Kosmos mit Feder in die nächste Scheibe wechseln.
{TANK} P1: Ein Tank hält Morium am Portal und sammelt Leerenkugeln; der andere hält das Hauptziel. Dunkle Hand defensiv. P2: Alleria und Riss-Simulakrum trennen. Risshieb bei 2-3 Stapeln tauschen. Scheibenwechsel nur geplant, weil Flüchtige Risse stapeln. P3: Tank-Fessel zuletzt brechen.
{DD} P1: Feste Pfeilplanung auf Demair -> Vorelus -> Morium. Tropfen/Leerenkugeln in den Stack ziehen und cleaven. P2: Kosmische Barriere sofort brechen. Leerenbrut mit Markierung freischalten, kicken und vor 100 Energie töten. Leerenpirscherstachel per Pfeil mit reinigen, wenn eure Gruppe es so spielt. P3: Alles in den Boss drücken, Fesseln sauber nacheinander brechen und Feder nicht verpassen.
{HEAL} Größte Checks sind Widerhallende Dunkelheit, Nullkorona, Sternenemission, Kosmische Barriere, Leerenpirscherstachel, Schwerkraftkollaps und Verschlingender Kosmos. Nullkorona nur dispellen, wenn das Ziel sonst stirbt.
{HC} Leerenausstoß kommt öfter. Silberschlag-Sperrfeuer bestraft den nächsten Pfeil kurz danach hart. Griff der Leere trifft zwei Spieler gleichzeitig.
{M} Silberrückstand auf Wächterzielen aktiv nutzen. Pfeil-Linien, Griff der Leere und Plattformwechsel müssen perfekt sitzen. Fehler bei Sperrfeuer oder Scheibenwechsel kippen den Pull sofort.
]=],

	BOSS_GUIDES_BOSS_CHIMAERUS_NAME = "Chimaerus, der Ungeträumte Gott",
	BOSS_GUIDES_BOSS_CHIMAERUS_BODY = [=[
Allgemein: Raid vor Pull in zwei feste Gruppen teilen. Alnstaub-Aufruhr immer seitlich mit der zugewiesenen Gruppe soaken, damit sie Alnsicht bekommt; Gruppen wegen Rissanfälligkeit abwechseln. Rissgruppe folgt ihrem Tank auf die Manifestationen, normale Gruppe spielt Boss und wechselt auf Adds, sobald sie freigeschaltet sind. Kleine Adds am großen Add stacken. Furchterregenden Schrei und Essenzblitz sofort kicken. Spieler mit Verzehrendes Miasma gehen auf eine Pfütze und lassen dort dispellen. Nie im Raid dispellen. Ziel von Reißendes Schlitzen tritt raus. Adds nie vom Boss fressen lassen. Bei 100 Energie kommt Verzehren, Knockback und Zwischenphase. In der Zwischenphase Verderbte Verwüstung dodgen, Pfützen löschen und alle Adds vor Gefräßiger Sturzflug töten.
{TANK} Kolossale Schrecken sofort übernehmen und defensiv tanken. Die Aufruhr-Soakgruppe immer sauber mitnehmen und im Riss führen.
{DD} Im Riss erst Alnschleier brechen, dann große und kleine Adds cleaven. In der Realität den Boss drücken und sofort auf freigeschaltete Adds wechseln. Keine Manifestation durchlassen. Flugphase komplett dodgen.
{HEAL} Risskrankheit ist ein großer Absorb-Check. CDs für Ätzenden Schleim, Kannibalisierte Essenz, Verzehren und Gefräßiger Sturzflug einteilen. Miasma-Dispels ansagen und nicht doppeln.
{HC} Verzehrendes Miasma löscht Pfützen beim Dispellen. Platz dauerhaft sauber halten.
{M} Dissonanz: beide Realm-Gruppen dürfen nicht ineinander stehen. Risswahnsinn hat feste Tauschpartner; ein Spieler aus der Realität stellt sich auf das Ziel im Riss und tauscht die Reiche. Eine Marke ist immer auf einem Heiler. Vor der Zwischenphase kommt noch ein Alnstaub-Aufruhr. In der Flugphase spawnen Adds auch im Riss.
]=],
	BOSS_GUIDES_SPELL_NAMES = {
		["Oblivion's Wrath"] = "Zorn der Auslöschung",
		["Shadow Phalanx"] = { spellID = 1284786, localizedName = "Schattenphalanx" },
		["Dark Barrage"] = "Dunkelsalve",
		["Void Infusion"] = "Leereninfusion",
		["Dark Uproar"] = { spellID = 1249251, localizedName = "Dunkle Verwerfung" },
		["Black Miasma"] = { spellID = 1275059, localizedName = "Schwarzes Miasma" },
		["Blackening Wounds"] = { spellID = 1265540, localizedName = "Schwärzende Wunden" },
		["Cosmic Shell"] = { spellID = 1280035, localizedName = "Kosmischer Panzer" },
		["Void Marked"] = { spellID = 1280015, localizedName = "Leerenmarkiert" },
		["Pitch Bulwark"] = { spellID = 1255702, localizedName = "Bollwerk errichten" },
		["Void Fall"] = "Leerensturz",
		["Rising Darkness"] = { spellID = 1255749, localizedName = "Aufziehende Dunkelheit" },
		["Dark Resilience"] = { spellID = 1264164, localizedName = "Dunkle Resilienz" },
		["Overpowering Pulse"] = { spellID = 1244419, localizedName = "Überwältigender Puls" },
		["Blisterburst"] = { spellID = 1259186, localizedName = "Pustelbersten" },
		["Void Breath"] = { spellID = 1256855, localizedName = "Leerenatem" },
		["Primordial Roar"] = { spellID = 1260046, localizedName = "Urzeitliches Brüllen" },
		["Creep Spit"] = { spellID = 1273159, localizedName = "Kriecherspritzer" },
		["Shadowclaw Slash"] = { spellID = 1244012, localizedName = "Schattenklauenhieb" },
		["Dark Goo"] = "Dunkler Schleim",
		["Smashed"] = "Zerschmettert",
		["Torturous Extract"] = "Quälender Extrakt",
		["Shattering Twilight"] = "Zerschmetterndes Zwielicht",
		["Destabilizing Strikes"] = "Destabilisierende Schläge",
		["Concentrated Void"] = "Konzentrierte Leere",
		["Fractured Images"] = "Zersplitterte Abbilder",
		["Entropic Unraveling"] = "Entropische Entfesselung",
		["Twisting Obscurity"] = "Windende Obskurität",
		["Despotic Command"] = "Despotischer Befehl",
		["Oppressive Darkness"] = "Erdrückende Dunkelheit",
		["Dark Radiation"] = "Dunkle Strahlung",
		["Enduring Void"] = "Anhaltende Leere",
		["Nexus Shield"] = "Nexusschild",
		["Twilight Bond"] = "Zwielichtband",
		["Vaelwing"] = "Vaelflügel",
		["Rakfang"] = "Rakzahn",
		["Nullbeam"] = "Nullstrahl",
		["Gloom"] = "Düsterkeit",
		["Dread Breath"] = "Schreckensatem",
		["Nullzone"] = "Nullzone",
		["Shadowmark"] = "Schattenmal",
		["Nullsnap"] = "Nullbruch",
		["Midnight Flames"] = "Mitternachtsflammen",
		["Gloomtouched"] = "Von Düsterkeit berührt",
		["Diminish"] = "Schwächung",
		["Nullscatter"] = "Nullstreuung",
		["Cosmosis"] = "Kosmosis",
		["Retribution"] = "Vergeltung",
		["Judgment"] = "Richturteil",
		["Exorcism"] = "Exorzismus",
		["Execution Sentence"] = "Todesurteil",
		["Sacred Shield"] = "Heiliges Schild",
		["Blinding Light"] = "Blendendes Licht",
		["Divine Hammer"] = "Göttlicher Hammer",
		["Light Infused"] = "Lichtinfundiert",
		["Searing Radiance"] = "Sengende Strahlkraft",
		["Tyr's Wrath"] = "Tyrs Zorn",
		["Divine Toll"] = "Göttliches Läuten",
		["Consecration"] = "Weihe",
		["Zealous Spirit"] = "Eifergeist",
		["Divine Consecration"] = "Göttliche Weihe",
		["Echoing Darkness"] = "Widerhallende Dunkelheit",
		["Empowering Darkness"] = "Verstärkende Dunkelheit",
		["Rift Slash"] = "Risshieb",
		["Silverstrike"] = "Silberschlag",
		["Cosmic Barrier"] = "Kosmische Barriere",
		["Coalesced Form"] = "Koaleszierte Form",
		["Null Corona"] = "Nullkorona",
		["Voidstalker Sting"] = "Leerenpirscherstachel",
		["Devouring Cosmos"] = "Verschlingender Kosmos",
		["Void Expulsion"] = "Leerenausstoß",
		["Barrage"] = "Sperrfeuer",
		["Silver Residue"] = "Silberrückstand",
		["Grasp of Emptiness"] = "Griff der Leere",
		["Upheaval"] = "Aufruhr",
		["Colossal Horrors"] = "Kolossale Schrecken",
		["Alnshroud"] = "Alnschleier",
		["Fearsome Cry"] = "Furchterregender Schrei",
		["Essence Bolt"] = "Essenzblitz",
		["Ravenous Dive"] = "Gefräßiger Sturzflug",
		["Rift Sickness"] = "Risskrankheit",
		["Caustic Phlegm"] = "Ätzender Schleim",
		["Cannibalized Essence"] = "Kannibalisierte Essenz",
		["Consuming Miasma"] = "Verzehrendes Miasma",
		["Alndust Essence"] = "Alnstaubessenz",
		["Rift Madness"] = "Risswahnsinn",
		["Dissonance"] = "Dissonanz",
		["Umbral Collapse"] = { spellID = 1249262, localizedName = "Umbralkollaps" },
		["March of the Endless"] = { spellID = 1251583, localizedName = "Marsch der Unendlichen" },
	},
	STREAMER_PLANNER_TITLE = "Gruppenplaner",
	STREAMER_PLANNER_DESC = "Ein kleines transparentes Overlay für Stream-Situationen, in dem du Zusagen schnell auf feste Dungeon- oder Raid-Slots verteilen kannst.",
	STREAMER_PLANNER_USAGE_HINT = "Klick in Vorschau oder Overlay auf einen Slot, trage den Namen ein und bestätige mit Enter. Rechtsklick auf einen Slot leert ihn direkt wieder.",
	STREAMER_PLANNER_PREVIEW_HINT = "Die Vorschau spiegelt dieselben Daten wie das Overlay. Du kannst beide Ansichten direkt zum Eintragen verwenden.",
	STREAMER_PLANNER_SETTINGS_HINT = "Hier steuerst du Modus, Sichtbarkeit und Position des Planungs-Overlays für den Stream.",
	STREAMER_PLANNER_SHOW_OVERLAY = "Planungs-Overlay anzeigen",
	STREAMER_PLANNER_SHOW_OVERLAY_HINT = "Blendet das transparente Overlay ein oder aus, ohne die eingetragenen Namen zu verlieren.",
	STREAMER_PLANNER_LOCK_OVERLAY = "Planungs-Overlay fixieren",
	STREAMER_PLANNER_LOCK_OVERLAY_HINT = "Sperrt das Overlay an seiner aktuellen Position, damit es im Stream nicht versehentlich verschoben wird.",
	STREAMER_PLANNER_MODE = "Planungsmodus",
	STREAMER_PLANNER_MODE_HINT = "Wechselt zwischen einem 5er-Dungeonaufbau und vier Raid-Gruppen mit je fünf Plätzen.",
	STREAMER_PLANNER_MODE_DUNGEON = "Dungeon",
	STREAMER_PLANNER_MODE_RAID = "Raid",
	STREAMER_PLANNER_DESTINATION = "Ziel",
	STREAMER_PLANNER_DESTINATION_HINT = "Hier schreibst du direkt rein, wohin es geht, zum Beispiel den Raidnamen, die Instanz oder einen Treffpunkt.",
	STREAMER_PLANNER_DESTINATION_EMPTY = "Noch kein Ziel eingetragen",
	STREAMER_PLANNER_DESTINATION_MANUAL = "Manuell eingeben",
	STREAMER_PLANNER_DESTINATION_CATEGORY = "Pool",
	STREAMER_PLANNER_DESTINATION_SUGGESTION = "Vorschlag",
	STREAMER_PLANNER_DESTINATION_CATEGORY_S1 = "S1",
	STREAMER_PLANNER_DESTINATION_CATEGORY_DELVES = "Tiefen",
	STREAMER_PLANNER_DESTINATION_CATEGORY_MIDNIGHT = "Midnight",
	STREAMER_PLANNER_DESTINATION_CATEGORY_RAIDS = "Raids",
	STREAMER_PLANNER_DESTINATION_EDIT = "Ziel bearbeiten",
	STREAMER_PLANNER_DESTINATION_EDIT_HINT = "Trage hier ein, wohin die Gruppe oder der Raid geplant ist.",
	STREAMER_PLANNER_DESTINATION_KEYSTONE = "Keystufe",
	STREAMER_PLANNER_DESTINATION_S1_MAGISTERS_TERRACE = "Magisterterrasse",
	STREAMER_PLANNER_DESTINATION_S1_MAISARA_CAVERNS = "Maisara-Höhlen",
	STREAMER_PLANNER_DESTINATION_S1_NEXUS_POINT_XENAS = "Nexuspunkt Xenas",
	STREAMER_PLANNER_DESTINATION_S1_WINDRUNNER_SPIRE = "Windläuferturm",
	STREAMER_PLANNER_DESTINATION_S1_ALGETHAR_ACADEMY = "Akademie von Algeth'ar",
	STREAMER_PLANNER_DESTINATION_S1_PIT_OF_SARON = "Grube von Saron",
	STREAMER_PLANNER_DESTINATION_S1_SEAT_OF_THE_TRIUMVIRATE = "Sitz des Triumvirats",
	STREAMER_PLANNER_DESTINATION_S1_SKYREACH = "Himmelsnadel",
	STREAMER_PLANNER_DESTINATION_DELVE_ATAL_AMAN = "Atal'Aman",
	STREAMER_PLANNER_DESTINATION_DELVE_COLLEGIATE_CALAMITY = "Akademisches Chaos",
	STREAMER_PLANNER_DESTINATION_DELVE_DEN_OF_ECHOES = "Hort der Echos",
	STREAMER_PLANNER_DESTINATION_DELVE_PARHELION_PLAZA = "Parhelionplatz",
	STREAMER_PLANNER_DESTINATION_DELVE_SHADOWGUARD_POINT = "Schattenwachtposten",
	STREAMER_PLANNER_DESTINATION_DELVE_SUNKILLER_SANCTUM = "Sonnenkillersanktum",
	STREAMER_PLANNER_DESTINATION_DELVE_THE_DARKWAY = "Der Dunkelgang",
	STREAMER_PLANNER_DESTINATION_DELVE_THE_GRUDGE_PIT = "Die Grollgrube",
	STREAMER_PLANNER_DESTINATION_DELVE_THE_GULF_OF_MEMORY = "Der Golf der Erinnerung",
	STREAMER_PLANNER_DESTINATION_DELVE_THE_SHADOW_ENCLAVE = "Die Schattenenklave",
	STREAMER_PLANNER_DESTINATION_DELVE_TORMENTS_RISE = "Turm der Qualen",
	STREAMER_PLANNER_DESTINATION_DELVE_TWILIGHT_CRYPTS = "Zwielichtkrypten",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_WINDRUNNER_SPIRE = "Windläuferturm",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_MAGISTERS_TERRACE = "Magisterterrasse",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_MURDER_ROW = "Mördergasse",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_DEN_OF_NALORAKK = "Hort von Nalorakk",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_MAISARA_CAVERNS = "Maisara-Höhlen",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_THE_BLINDING_VALE = "Das blendende Tal",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_VOIDSCAR_ARENA = "Arena der Leerennarbe",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_NEXUS_POINT_XENAS = "Nexuspunkt Xenas",
	STREAMER_PLANNER_DESTINATION_RAID_VOIDSPIRE = "Leerspitz",
	STREAMER_PLANNER_DESTINATION_RAID_DREAMRIFT = "Traumriss",
	STREAMER_PLANNER_DESTINATION_RAID_MARCH_ON_QUEL_DANAS = "Marsch auf Quel'Danas",
	STREAMER_PLANNER_CLASS = "Klasse",
	STREAMER_PLANNER_CLASS_NONE = "Keine Klasse",
	STREAMER_PLANNER_SPEC = "Spezialisierung",
	STREAMER_PLANNER_SPEC_NONE = "Keine Spec",
	STREAMER_PLANNER_SCALE = "Overlay-Skalierung",
	STREAMER_PLANNER_SCALE_HINT = "Passt die Größe des transparenten Overlays an, ohne Einträge oder Positionen zu verändern.",
	STREAMER_PLANNER_TIMER_DURATION = "Timerdauer",
	STREAMER_PLANNER_TIMER_DURATION_VALUE = "%d Min.",
	STREAMER_PLANNER_TIMER_DURATION_HINT = "Legt fest, mit welcher Dauer der Stream-Timer startet und worauf Reset zurücksetzt.",
	STREAMER_PLANNER_RESET_POSITION_HINT = "Setzt das Overlay zurück in die Ausgangsposition nahe der Bildschirmmitte.",
	STREAMER_PLANNER_CLEAR_LAYOUT = "Aktuelles Layout leeren",
	STREAMER_PLANNER_CLEAR_LAYOUT_HINT = "Entfernt alle Namen nur aus dem aktuell gewählten Dungeon- oder Raid-Modus.",
	STREAMER_PLANNER_CLEAR_ALL = "Alles leeren",
	STREAMER_PLANNER_CLEAR_ALL_HINT = "Löscht Dungeon- und Raid-Planung komplett, falls du einen frischen Stand brauchst.",
	STREAMER_PLANNER_OVERLAY_CLEAR_ALL = "Alle leeren",
	STREAMER_PLANNER_EDIT_HINT = "Tipp: Linksklick bearbeitet einen Slot, Rechtsklick leert ihn sofort. So kannst du Meldungen aus dem Stream ohne Umwege sortieren.",
	STREAMER_PLANNER_OVERLAY_TITLE = "Gruppenplaner",
	STREAMER_PLANNER_OVERLAY_CLOSE_TOOLTIP = "Overlay ausblenden",
	STREAMER_PLANNER_OVERLAY_CLOSE_TOOLTIP_HINT = "Blendet den Gruppenplaner aus. Über die Modulseite kannst du ihn jederzeit wieder einblenden.",
	STREAMER_PLANNER_OVERLAY_SETTINGS_BUTTON = "Menü",
	STREAMER_PLANNER_OVERLAY_SETTINGS_TOOLTIP = "Moduleinstellungen öffnen",
	STREAMER_PLANNER_OVERLAY_SETTINGS_TOOLTIP_HINT = "Springt direkt zur Gruppenplaner-Seite im Addonfenster.",
	STREAMER_PLANNER_TIMER = "Timer",
	STREAMER_PLANNER_TIMER_START = "Start",
	STREAMER_PLANNER_TIMER_PAUSE = "Pause",
	STREAMER_PLANNER_TIMER_RESET = "Reset",
	STREAMER_PLANNER_TIMER_RUNNING = "Läuft",
	STREAMER_PLANNER_TIMER_PAUSED = "Pausiert",
	STREAMER_PLANNER_TIMER_EXPIRED = "Zeit abgelaufen: Randoms suchen",
	STREAMER_PLANNER_EMPTY_SLOT = "frei",
	STREAMER_PLANNER_SLOT_EDIT = "Slot bearbeiten",
	STREAMER_PLANNER_SLOT_EDIT_HINT = "Trage hier den Namen oder eine kurze Notiz für diesen Platz ein.",
	STREAMER_PLANNER_SAVE_SLOT = "Speichern",
	STREAMER_PLANNER_CLEAR_SLOT = "Leeren",
	STREAMER_PLANNER_ROLE_TANK = "Tank",
	STREAMER_PLANNER_ROLE_HEALER = "Heiler",
	STREAMER_PLANNER_ROLE_DPS1 = "DPS 1",
	STREAMER_PLANNER_ROLE_DPS2 = "DPS 2",
	STREAMER_PLANNER_ROLE_DPS3 = "DPS 3",
	STREAMER_PLANNER_RAID_SUMMARY = "Tanks: %d   Heiler: %d   DDs: %d",
	STREAMER_PLANNER_RAID_GROUP = "Gruppe %d",
	STREAMER_PLANNER_RAID_SLOT = "G%d / %d",
	MARKER_BAR_DESC = "Eine kompakte Overlay-Leiste für Zielmarkierungen und Bodenmarker. Normaler Klick markiert dein aktuelles Ziel, Shift-Klick setzt die passende Bodenmarke.",
	MARKER_BAR_USAGE_HINT = "Normalklick setzt die Zielmarkierung. Shift-Klick aktiviert die passende Bodenmarke. Die Leiste bleibt bewusst klein, transparent und direkt im Blickfeld.",
	MARKER_BAR_PERMISSION_HINT = "Hinweis: Markierungen funktionieren nur, wenn dir die Gruppe oder der Schlachtzug das Setzen von Markern erlaubt.",
	MARKER_BAR_SHOW_OVERLAY = "Markerleiste anzeigen",
	MARKER_BAR_LOCK_OVERLAY = "Markerleiste fixieren",
	MARKER_BAR_SCALE = "Skalierung",
	MARKER_BAR_SCALE_HINT = "Passt die Größe der transparenten Leiste an, ohne die Belegung der Marker zu verändern.",
	MARKER_BAR_RESET_POSITION = "Leistenposition zurücksetzen",
	MARKER_BAR_OVERLAY_HINT = "Klick = Ziel markieren | Shift = Bodenmarker",
	MARKER_BAR_DRAG_HINT = "Zum Verschieben die Leiste entsperren und am Rand ziehen.",
	CAMERA_DISTANCE_HINT = "Setzt die maximale Kamera-Distanz auf den Standardwert oder auf den maximalen Wert und zieht die Einstellung nach dem Einloggen erneut nach.",
	CURRENT_SETTING = "Aktuelle Einstellung:",
	CAMERA_DISTANCE_MAX = "Max Distance",
	CAMERA_DISTANCE_QUESTION = "?",
	CAMERA_DISTANCE_MODE_MAX = "max",
	CAMERA_DISTANCE_MODE_STANDARD = "standard",
	CAMERA_DISTANCE_MODE_CUSTOM = "custom",
	CAMERA_DISTANCE_MODE_UNKNOWN = "unknown",
	CAMERA_DISTANCE_STATUS_MAX = "Max Distance (%s)",
	CAMERA_DISTANCE_STATUS_STANDARD = "Standard (%s)",
	CAMERA_DISTANCE_STATUS_CUSTOM = "Benutzerdefiniert (%s)",
	CAMERA_DISTANCE_STATUS_UNKNOWN = "Unbekannt",
	AUTOREPAIR_GUILD_DONE = "Beavis QoL: Reparatur über die Gilde durchgeführt.",
	AUTOREPAIR_DONE = "Beavis QoL: Reparatur für %s durchgeführt.",
	AUTOSELL_UNKNOWN_ITEM = "Unbekanntes Item",
	AUTOSELL_SUMMARY = "Beavis QoL: %d Junk-Item(s) verkauft für %s.",
	STANDARD = "Standard",

	VERSIONS_INFO_TITLE = "%s - Versionsinfos",
	VERSIONS_INFO_DESC = "Hier findest du die wichtigsten Infos zur installierten Version und einen Ingame-Hinweis, wenn dir jemand mit einer höheren BeavisQoL-Version begegnet.",
	CURRENT_VERSION = "Aktuelle Version",
	RELEASE_DATE = "Release-Datum",
	PROGRAMMER = "Programmierer",
	SUPPORTED_GAME_VERSION = "Unterstützte Spielversion",
	TOC_VERSION = "TOC Version",
	VERSION_CHECK = "Versionsabgleich",
	VERSION_CHECK_AVAILABLE = "Neue Version verfügbar: %s",
	VERSION_CHECK_SEEN_AT = "Gesehen bei %s über %s. Installiert ist derzeit %s.",
	VERSION_CHECK_CHANNEL = "einen Gruppenkanal",
	VERSION_CHECK_HINT = "Hinweis: Der Vergleich funktioniert über Gruppe, Raid, Instanzchat oder Gilde und nicht direkt über GitHub.",
	VERSION_CHECK_CURRENT = "Aktuell",
	VERSION_CHECK_CURRENT_TEXT = "Sobald ein Update verfügbar ist, bekommst du hier eine Information.",
	VERSION_CHECK_CURRENT_SUBTEXT = "Installiert: %s | Release-Datum: %s",
	VERSION_COMPARE_NOW = "Jetzt abgleichen",
	VERSION_RELEASE_LINK = "Release-Link",
	CONTACT_TITLE = "Mithelfen & Kontakt",
	CONTACT_TEXT = "Wenn du Feedback geben oder neue Ideen einreichen möchtest, kannst du direkt über die Beavismania-Webseite Kontakt aufnehmen.",
	SEND_FEEDBACK = "Feedback senden",
	SUBMIT_IDEA = "Idee einschicken",
	RELEASES_POPUP = "BeavisQoL Releases",
	FEEDBACK_POPUP = "Feedback senden",
	IDEA_POPUP = "Idee einschicken",

	DAMAGE_TEXT_DESC = "Hier kannst du die Blizzard-Schadenszahlen optisch anpassen. Schrift und Bewegungsverhalten werden direkt über die vorhandenen Combat-Text-Systeme umgestellt.",
	DAMAGE_TEXT_CONFLICT = "Konflikt: NiceDamage ist geladen und kann deinen Combat Text überschreiben. Bitte NiceDamage für diesen Charakter deaktivieren, wenn du Beavis QoL nutzen willst.",
	DAMAGE_TEXT_ENABLE_TITLE = "Eigene Combat Textanpassungen verwenden",
	DAMAGE_TEXT_ENABLE_HINT = "Ersetzt die Blizzard-Kampftext-Schrift und passt die Bewegung der Schadenszahlen über Scale, Gravity und Ramp Duration an.",
	DAMAGE_TEXT_APPEARANCE_HINT = "Die mitgelieferten Fonts aus dem Font-Ordner des Addons stehen dir direkt in der Auswahl zur Verfügung, inklusive Pepsi Modern. Scale, Gravity und Ramp Duration wirken direkt.",
	DAMAGE_TEXT_RESTART_HINT = "Nach einem Font-Wechsel muss das Spiel komplett beendet und neu gestartet werden, damit die Änderung sicher übernommen wird.",

	LFG_DESC = "Hier findest du Komfortfunktionen für die Premade-Gruppensuche.",
	FLAGS_TITLE = "Länderflaggen",
	FLAGS_HINT = "Zeigt in der Premade-Gruppensuche neben Bewerbern eine kleine Flagge auf Basis ihres Realms an.",
	EASY_LFG_TITLE = "Easy LFG",
	EASY_LFG_HINT = "Blendet für deine eigene Gruppenanzeige ein kleines transparentes Applicant-Overlay ein, damit du Bewerber ohne das große Blizzard-Fenster sehen und einladen kannst.",
	EASY_LFG_SHOW_OVERLAY = "Easy-LFG-Overlay aktivieren",
	EASY_LFG_SHOW_OVERLAY_HINT = "Zeigt das kompakte Applicant-Fenster automatisch an, sobald deine eigene Gruppe aktiv ist.",
	EASY_LFG_LOCK_OVERLAY = "Easy-LFG-Overlay fixieren",
	EASY_LFG_LOCK_OVERLAY_HINT = "Sperrt die Position des kleinen Applicant-Fensters, damit es nicht versehentlich verschoben wird.",
	EASY_LFG_SCALE = "Overlay-Skalierung",
	EASY_LFG_SCALE_HINT = "Passt die Größe des Easy-LFG-Fensters an, ohne Einträge oder Position zu verändern.",
	EASY_LFG_BACKGROUND_ALPHA = "Hintergrund-Transparenz",
	EASY_LFG_BACKGROUND_ALPHA_HINT = "Steuert, wie deutlich der Hintergrund des Applicant-Fensters sichtbar bleibt.",
	EASY_LFG_RESET_HINT = "Setzt das Easy-LFG-Fenster zurück in seine Startposition rechts neben deiner Figur.",
	INVITE_TIMER_TITLE = "Einladungs-Timer",
	INVITE_TIMER_HINT = "Fügt direkt in Bereitschaftsfenstern wie Dungeonbrowser, LFR, Arena und Schlachtfeld eine kleine Countdown-Leiste mit Sekundenanzeige ein.",
	INVITE_TIMER_ENABLED = "Einladungs-Timer anzeigen",
	INVITE_TIMER_ENABLED_HINT = "Zeigt in unterstützten Einladungsfenstern eine kompakte Countdown-Leiste, bis die Einladung abläuft.",
	INVITE_TIMER_COUNTDOWN_SOUND = "Countdown-Sound ab 5 Sekunden",
	INVITE_TIMER_COUNTDOWN_SOUND_HINT = "Spielt für die letzten fünf Sekunden eine Sprachansage mit five, four, three, two, one ab.",
	EASY_LFG_OVERLAY_TITLE = "Easy LFG",
	EASY_LFG_OVERLAY_SUMMARY = "%d Bewerber | %d Spieler",
	EASY_LFG_OVERLAY_EMPTY = "Noch keine Bewerber in der Warteschlange.",
	EASY_LFG_OVERLAY_NO_GROUP = "Easy LFG erscheint automatisch, sobald deine eigene Gruppe aktiv ist.",
	EASY_LFG_OVERLAY_NO_GROUP_SHORT = "Keine aktive Gruppe",
	EASY_LFG_OVERLAY_MORE = "+%d weitere Spieler nicht angezeigt",
	EASY_LFG_OVERLAY_RESIZE_HINT = "Unten rechts ziehen zum Skalieren der Fläche.",
	EASY_LFG_OVERLAY_CLOSE_TOOLTIP = "Easy LFG ausblenden",
	EASY_LFG_OVERLAY_CLOSE_TOOLTIP_HINT = "Blendet das Overlay für die aktuelle aktive Gruppe aus. Bei der nächsten eigenen Listung erscheint es wieder automatisch.",
	EASY_LFG_OVERLAY_PIN = "Pin",
	EASY_LFG_OVERLAY_UNPIN = "Lösen",
	EASY_LFG_OVERLAY_PIN_TOOLTIP = "Overlay fixieren",
	EASY_LFG_OVERLAY_UNPIN_TOOLTIP = "Fixierung lösen",
	EASY_LFG_OVERLAY_PIN_TOOLTIP_HINT = "Sperrt oder entsperrt die Position des Easy-LFG-Overlays.",
	EASY_LFG_DECLINE = "Ablehnen",
	EASY_LFG_INVITE = "Einladen",
	EASY_LFG_ITEM_LEVEL = "ilvl %s",
	EASY_LFG_SCORE = "Score %d",
	EASY_LFG_GROUP_BADGE = "%d Spieler",
	EASY_LFG_MEMBER_INDEX = "%d/%d",
	EASY_LFG_STATUS_APPLIED = "Beworben",
	EASY_LFG_STATUS_INVITED = "Eingeladen",
	EASY_LFG_STATUS_INVITE_ACCEPTED = "Invite angenommen",
	EASY_LFG_STATUS_DECLINED = "Abgelehnt",
	EASY_LFG_STATUS_INVITE_DECLINED = "Invite abgelehnt",
	EASY_LFG_STATUS_INACTIVE = "Inaktiv",

	PET_STUFF_DESC = "Hier findest du kleine Komfortfunktionen rund um Begleiter und Pets.",
	AUTO_RESPAWN_PET_TITLE = "Auto Respawn Pet",
	AUTO_RESPAWN_PET_HINT = "Beschwört dein zuletzt aktives Begleiter-Pet nach dem Auf- und Abmounten automatisch erneut. Das Rufen ist nur außerhalb des Kampfes möglich.",

	ITEM_GUIDE_EYEBROW = "Fortschritt",
	ITEM_GUIDE_TITLE = "Midnight S1 Itemlevel-Kompass",
	ITEM_GUIDE_SUBTITLE = "Upgradepfade, Crafting, Dungeons, Raid und Tiefen kompakt auf einer Seite.",
	ITEM_GUIDE_DESC = "Die Werte sind als schnelle Saisonreferenz gedacht. Besonders die Raid-Itemlevel sind bewusst als Richtwerte markiert, damit die Seite im Alltag wie ein ruhiges Nachschlagewerk funktioniert und nicht wie eine gequetschte Zahlenliste.",
	SEASON_REFERENCE = "Saison-Referenz",
	ITEM_GUIDE_BADGE_TEXT = "20 Wappen pro Rang\nRaidwerte = ca.-Angaben",
	ITEM_GUIDE_LEGEND = "|cff45ff6eAbenteurer|r  -  |cff2e94ffVeteran|r  -  |cffba57ffChampion|r  -  |cffff9220Held|r  -  |cffffe033Mythisch|r",
	ITEM_GUIDE_UPGRADE_CARD_TITLE = "Wappenpfade",
	ITEM_GUIDE_UPGRADE_CARD_SUBTITLE = "Upgradepfade und Wappen",
	ITEM_GUIDE_UPGRADE_CARD_NOTE = "20 Wappen pro Rang, Sparstellen direkt markiert.",
	ITEM_GUIDE_PATH_ADVENTURER = "Abenteurer",
	ITEM_GUIDE_PATH_VETERAN = "Veteran",
	ITEM_GUIDE_PATH_CHAMPION = "Champion",
	ITEM_GUIDE_PATH_HERO = "Held",
	ITEM_GUIDE_PATH_MYTH = "Mythisch",
	ITEM_GUIDE_SAVE_FOR_RUNED = "auf Runenwappen sparen",
	ITEM_GUIDE_SAVE_FOR_GILDED = "auf Vergoldete sparen",
	ITEM_GUIDE_HEADER_PATH_RANK = "Pfad / Rang",
	ITEM_GUIDE_HEADER_CRESTS = "Wappen",
	ITEM_GUIDE_HEADER_QUALITY = "Qualität",
	ITEM_GUIDE_HEADER_SOURCE = "Quelle",
	ITEM_GUIDE_HEADER_END_REWARD = "Endbelohnung",
	ITEM_GUIDE_HEADER_GREAT_VAULT = "Große Schatzkammer",
	ITEM_GUIDE_HEADER_DIFFICULTY = "Schwierigkeit",
	ITEM_GUIDE_HEADER_EARLY = "Früh",
	ITEM_GUIDE_HEADER_MID = "Mitte",
	ITEM_GUIDE_HEADER_LATE = "Spät",
	ITEM_GUIDE_HEADER_END = "Ende",
	ITEM_GUIDE_HEADER_LEVEL = "Stufe",
	ITEM_GUIDE_HEADER_MAP_DROP = "Karten-Drop",
	ITEM_GUIDE_LABEL_HEROIC = "Heroisch",
	ITEM_GUIDE_LABEL_MYTHIC = "Mythisch",
	ITEM_GUIDE_LABEL_RAID_FINDER = "Schlachtzugsbrowser",
	ITEM_GUIDE_LABEL_NORMAL = "Normal",
	ITEM_GUIDE_ABBR_ADVENTURER = "Abent.",
	ITEM_GUIDE_ABBR_VETERAN = "Vet.",
	ITEM_GUIDE_ABBR_CHAMPION = "Champ.",
	ITEM_GUIDE_ABBR_HERO = "Held",
	ITEM_GUIDE_ABBR_MYTH = "Myth",
	ITEM_GUIDE_CRAFTED_CARD_TITLE = "Crafting",
	ITEM_GUIDE_CRAFTED_CARD_SUBTITLE = "Hergestellte Itemlevel",
	ITEM_GUIDE_CRAFTED_CARD_NOTE = "Qualität und Zielpfad in einer kompakten Matrix.",
	ITEM_GUIDE_DUNGEON_CARD_TITLE = "Instanzen",
	ITEM_GUIDE_DUNGEON_CARD_SUBTITLE = "Dungeon und Große Schatzkammer",
	ITEM_GUIDE_DUNGEON_CARD_NOTE = "Heroisch, Mythisch und M+ auf einen Blick.",
	ITEM_GUIDE_RAID_CARD_TITLE = "Schlachtzug",
	ITEM_GUIDE_RAID_CARD_SUBTITLE = "Raid-Richtwerte",
	ITEM_GUIDE_RAID_CARD_NOTE = "Frühe bis späte Bosse als grobe Saisonreferenz.",
	ITEM_GUIDE_DELVE_CARD_TITLE = "Tiefen",
	ITEM_GUIDE_DELVE_CARD_SUBTITLE = "Tiefen und Wochenkiste",
	ITEM_GUIDE_DELVE_CARD_NOTE = "Endbelohnung, Karten-Drop und Große Schatzkammer.",
	ITEM_GUIDE_UPGRADE_FOOTNOTE = "Die roten Hinweise markieren Stellen, an denen sich die nächste Wappenfarbe meist besser aufhebt.",
	ITEM_GUIDE_RAID_FOOTNOTE = "Raid-Werte sind bewusst als ca.-Angaben formuliert und können je Boss leicht schwanken.",
	ITEM_GUIDE_FOOTER = "Ziel dieser Seite: schnelle Entscheidungen im Alltag. Ein Blick genügt, um Upgradepfad, Dungeon-Ziel oder Crafting-Stufe zu vergleichen.",

	LEVELTIME_TOOLTIP_TITLE = "Levelzeit-Tracker",
	LEVELTIME_TOOLTIP_TEXT = "Der Levelzeit-Tracker zählt nur die tatsächlich gespielte Zeit, während das Addon aktiv ist.",
	LEVEL_LABEL = "Level %d",
	CURRENT_LEVEL = "Aktuelles Level",
	TIME_ON_CURRENT_LEVEL = "Zeit auf aktuellem Level",
	TOTAL_TIME = "Gesamtzeit",
	TRACKED_LEVEL_TIMES = "Erfasste Levelzeiten",
	LEVEL_RUNNING = "läuft gerade",
	MAX_LEVEL_REACHED = "Maximallevel erreicht",
	MAX_LEVEL_CONGRATS = "Glückwunsch, du hast das Maximallevel erreicht.",

	QUESTCHECK_TITLE = "Quest Check",
	QUESTCHECK_DESC = "Prüft, ob eine Quest bereits erledigt ist. Du kannst direkt eine Quest-ID, einen WoWHead-Link oder einen exakten Questnamen eingeben.",
	QUEST_SEARCH = "Quest suchen",
	QUEST_SEARCH_HINT = "Beispiele: Quest ID 12345, ein exakter Questname oder https://www.wowhead.com/quest=12345",
	CHECK_QUEST = "Quest prüfen",
	RESULT = "Ergebnis",
	QUESTCHECK_RESULT_HINT = "Hier erscheint nach der Suche der Abschlussstatus der Quest.",
	QUESTCHECK_NO_SEARCH = "Noch keine Suche ausgeführt.",
	WOWHEAD_LINK = "WoWHead-Link",
	WOWHEAD_SEARCH = "WoWHead-Suche",
	LINKS_COPY_DIALOG = "Links werden im Copy-Dialog angezeigt.",
	QUESTCHECK_INPUT_MISSING = "Bitte eine Quest-ID, einen exakten Questnamen oder einen WoWHead-Link eingeben.",
	QUESTCHECK_SEARCH_RUNNING = "Suche läuft",
	QUESTCHECK_SCANNING = "Der Questname wird gegen lokal bekannte Questtitel geprüft. Das kann beim ersten Durchlauf einen Moment dauern.",
	QUESTCHECK_SCAN_PROGRESS = "Questnamen werden lokal durchsucht: %.0f%%",
	QUEST_DONE = "|cff55dd55Erledigt|r",
	QUEST_NOT_DONE = "|cffff6666Nicht erledigt|r",
	QUEST_IN_LOG = "im Questlog",
	QUEST_WARBAND_DONE = "warbandweit erledigt",
	QUEST_ID_LABEL = "Quest-ID %d",
	QUEST_RESULT_LINE = "[%d] %s - %s%s",
	QUEST_MORE_RESULTS = "|cffbfbfbf+ %d weitere Treffer|r",
	QUEST_SINGLE_SOURCE_ID = "Direkter ID-Check",
	QUEST_SINGLE_SOURCE_NAME = "Namenssuche",
	QUEST_SINGLE_TEXT = "Quest \"%s\" (ID %d) | %s",
	QUEST_SINGLE_CHAT = "Quest \"%s\" (ID %d) ist %s.",
	QUEST_SINGLE_CHAT_ACTIVE = " Sie ist aktuell im Questlog.",
	QUEST_SINGLE_CHAT_WARBAND = " Warbandweit ist sie bereits erledigt.",
	QUEST_WOWHEAD_TITLE = "Quest auf WoWHead",
	QUEST_MULTIPLE_STATE = "%d Treffer",
	QUEST_MULTIPLE_TEXT = "Mehrere Quests mit exakt diesem Namen wurden lokal gefunden. Bitte die passende Quest-ID aus der Liste wählen.",
	QUEST_MULTIPLE_CHAT = "%d Quests mit dem Namen \"%s\" gefunden. Details stehen im Quest Check Modul.",
	QUEST_UNRESOLVED_TEXT = "Der Questname konnte lokal nicht eindeutig auf eine Quest-ID aufgelöst werden. Mit Quest-ID ist die Prüfung am verlässlichsten.",
	QUEST_UNRESOLVED_TIPS = "Tipps:\n- exakten Questnamen verwenden\n- alternativ direkt eine Quest-ID oder einen WoWHead-Link einfügen",
	QUEST_UNRESOLVED_CHAT = "Questname \"%s\" konnte lokal nicht aufgelöst werden. Mit der Quest-ID ist der Check am sichersten.",
	QUEST_INPUT_MISSING_STATE = "Eingabe fehlt",
	QUEST_NOT_DONE_PLAIN = "nicht erledigt",
	QUEST_DONE_PLAIN = "erledigt",
	QUEST_ABANDON_TITLE = "Quest-Abbruch",
	QUEST_ABANDON_DESC = "Wähle gezielt aus, welche sichtbaren aktiven Quests abgebrochen werden sollen. Die Aktion wirkt sofort auf dein aktuelles Questlog und fragt vor dem Abbruch noch einmal nach.",
	QUEST_ABANDON_SELECT_ALL = "Alle markieren",
	QUEST_ABANDON_CLEAR_ALL = "Alle demarkieren",
	QUEST_ABANDON_SELECTED = "Markierte abbrechen",
	QUEST_ABANDON_UNAVAILABLE = "Quest-Abbruch ist über die aktuelle API hier nicht verfügbar.",
	QUEST_ABANDON_NONE = "Derzeit sind keine aktiven Quests im Questlog.",
	QUEST_ABANDON_SELECTION_COUNT = "%d von %d Quests markiert",
	QUEST_ABANDON_SELECTED_NONE = "Es sind keine Quests zum Abbrechen markiert.",
	QUEST_ABANDON_CONFIRM = "Sollen wirklich %d markierte Quest(s) abgebrochen werden?",
	QUEST_ABANDON_DONE = "%d Quest(s) wurden abgebrochen.",
	LIVE_PREVIEW = "Live-Vorschau",
	DISPLAY_POSITION = "Anzeige und Position",
	WINDOW_SCALE = "Fenster-Skalierung",
	BACKGROUND_ALPHA = "Hintergrund-Deckkraft",
	FONT_SIZE_OVERLAY = "Schriftgröße im Overlay",
	RESET_POSITION_HINT = "Setzt das Overlay wieder nach unten rechts an seine Startposition.",
	SHOW_OVERLAY = "Overlay anzeigen",
	LOCK_OVERLAY = "Overlay fixieren",

	STATS_TITLE = "Stats",
	STATS_DESC = "Zeigt deine wichtigsten Sekundärwerte in einem kleinen, dezenten Ingame-Fenster an. Die Vorschau unten nutzt bereits dein aktuelles Gear, Buffs und Procs.",
	STATS_PREVIEW_HINT = "So wirkt das kleine Stats-Fenster im Spiel: kompakt, sauber und bewusst unaufdringlich.",
	STATS_PREVIEW_FOOTER = "Schriftgröße, Skalierung und Transparenz greifen direkt in die Live-Vorschau ein.",
	STATS_SETTINGS_HINT = "Das Stats-Fenster ist frei beweglich, transparent und bewusst kompakt. Schriftgröße und Skalierung lassen sich getrennt anpassen.",
	STATS_SHOW_OVERLAY = "Stats-Fenster anzeigen",
	STATS_SHOW_OVERLAY_HINT = "Blendet außerhalb des Hauptfensters ein kleines Fenster mit deinen aktuellen Werten ein.",
	STATS_LOCK_OVERLAY = "Stats-Fenster fixieren",
	STATS_LOCK_OVERLAY_HINT = "Sperrt das freie Verschieben, sobald die Position für dich passt.",
	STATS_FONT_SIZE = "Schriftgröße im Stats-Fenster",
	STATS_RESET_HINT = "Setzt das kleine Stats-Fenster wieder an die Standardposition unten rechts.",

	WEEKLY_KEYS_DESC = "Zeigt dir die 8 höchsten Weekly-Keys in einem transparenten, fensterfreien Overlay. Auf den Zeilen 1, 4 und 8 steht direkt der jeweilige Weekly-Loot-Itemlevel.",
	WEEKLY_KEYS_PREVIEW_HINT = "Die Vorschau zeigt denselben cleanen Stil wie das Overlay im Spiel, aber absichtlich ohne sichtbaren Fensterrahmen.",
	WEEKLY_KEYS_PREVIEW_FOOTER = "Schriftgröße, Skalierung und Transparenz greifen direkt in die Live-Vorschau ein.",
	WEEKLY_KEYS_SETTINGS_HINT = "Das Overlay ist bewusst rahmenlos und dezent. Schriftgröße und Skalierung lassen sich getrennt anpassen, damit es kompakter wirken kann.",
	WEEKLY_KEYS_SHOW_OVERLAY = "Weekly-Keys-Overlay anzeigen",
	WEEKLY_KEYS_SHOW_OVERLAY_HINT = "Blendet außerhalb des Hauptfensters die Top-8-Keys mit Weekly-Loot-Hinweisen ein.",
	WEEKLY_KEYS_LOCK_OVERLAY = "Overlay fixieren",
	WEEKLY_KEYS_LOCK_OVERLAY_HINT = "Sperrt das freie Verschieben, sobald deine Position passt.",
	WEEKLY_KEYS_RESET_HINT = "Setzt das Overlay wieder nach unten rechts an seine Startposition.",
	WEEKLY_KEYS_HEROIC = "HC",
	WEEKLY_KEYS_MYTHIC = "Mythisch",
	WEEKLY_KEYS_HEROIC_RECORDED = "HC-Dungeon erfasst",
	WEEKLY_KEYS_MYTHIC_RECORDED = "Mythischer Dungeon erfasst",
	WEEKLY_KEYS_NAMELESS = "Dungeon ohne Namen erfasst",
	UNKNOWN_DUNGEON = "Unbekannter Dungeon",
	WEEKLY_KEYS_PLACEHOLDER = "Dungeon ohne Namen erfasst",
	WEEKLY_KEYS_NONE_THIS_WEEK = "Noch kein Dungeon in dieser Woche",
	WEEKLY_KEYS_NONE_WEEKLY = "Noch kein Weekly-Dungeon abgeschlossen",
	WEEKLY_KEYS_MORE_NEEDED = "Noch %d %s bis Weekly-Slot",
	DUNGEON_SINGULAR = "Dungeon",
	DUNGEON_PLURAL = "Dungeons",
	WEEKLY_KEYS_SUMMARY = "%d/8 Dungeons | Weekly-Loot %s / %s / %s",

	LOGGING_DESC = "Hier findest du Verkaufs-, Reparatur- sowie Gold-Logs für den aktuellen Charakter. Einnahmen und Ausgaben werden automatisch in passende Kategorien einsortiert, wenn WoW dafür einen erkennbaren Kontext liefert.",
	LOGGING_CLEANUP = "Zeitraum löschen",
	LOGGING_RETENTION_HINT = "Aufbewahrung: Verkaufslog und Reparaturlog 30 Tage, Gold Einnahmen und Ausgaben 1 Jahr.",
	LOGGING_CLEANUP_TITLE = "Log-Zeitraum löschen",
	LOGGING_CLEANUP_HINT = "Entfernt Einträge, die älter sind als der gewählte Zeitraum. Verkäufe und Reparaturen bleiben zusätzlich automatisch auf 30 Tage begrenzt.",
	LOGGING_SALES_TITLE = "Verkaufslog",
	LOGGING_SALES_HINT = "Zeigt die letzten Händlerverkäufe an, inklusive Auto Sell Junk. Einträge mit Itemdaten lassen sich per Klick aufklappen.",
	LOGGING_REPAIRS_TITLE = "Reparaturlog",
	LOGGING_REPAIRS_HINT = "Zeigt Tagessummen für Reparaturen. Tage mit Einzelreparaturen lassen sich per Klick aufklappen.",
	LOGGING_INCOME_TITLE = "Gold Einnahmen nach Kategorie",
	LOGGING_INCOME_HINT = "Summiert die gespeicherten Einnahmen nach Kategorien wie Verkauf, Quest oder Beute.",
	LOGGING_EXPENSE_TITLE = "Gold Ausgaben nach Kategorie",
	LOGGING_EXPENSE_HINT = "Summiert die gespeicherten Ausgaben nach Kategorien wie Reparatur, Händler oder Flugmeister.",
	LOGGING_STORED_SALES = "Gespeicherte Verkäufe: %d",
	LOGGING_TOTAL_SALES_GOLD = "Gesamtgold aus Verkäufen: %s",
	LOGGING_STORED_REPAIRS = "Gespeicherte Reparaturen: %d",
	LOGGING_DAILY_EXPAND_HINT = "Tagessummen lassen sich aufklappen.",
	LOGGING_NO_REPAIRS = "Noch keine Reparaturen protokolliert.",
	LOGGING_STORED_INCOME = "Gespeicherte Einnahmen: %d",
	LOGGING_TOTAL_INCOME = "Gesamtsumme: %s",
	LOGGING_STORED_EXPENSES = "Gespeicherte Ausgaben: %d",
	LOGGING_TOTAL_EXPENSES = "Gesamtsumme: %s",
	LOGGING_LATEST_ENTRIES = "Letzte Einträge:",
	DAYS_7 = "7 Tage",
	DAYS_30 = "30 Tage",
	DAYS_90 = "90 Tage",
	DAYS_365 = "1 Jahr",
	ALL = "Alles",
	DAILY = "Daily",
	WEEKLY = "Weekly",
	VAULT = "Vault",
	NO_ENTRIES = "Noch keine Einträge vorhanden.",
	UNKNOWN_ITEM = "Unbekanntes Item",
	LOGGING_SALE = "Verkauf",
	LOGGING_VENDOR_SALE = "Händlerverkauf",
	LOGGING_MAIL = "Post",
	LOGGING_MAILBOX = "Postfach",
	LOGGING_AUCTIONHOUSE = "Auktionshaus",
	LOGGING_TRADE = "Handel",
	LOGGING_QUEST = "Quest",
	LOGGING_QUEST_REWARD = "Questbelohnung",
	LOGGING_LOOT = "Beute",
	LOGGING_PICKED_UP = "Aufgesammelt",
	LOGGING_MISC = "Sonstiges",
	LOGGING_FLIGHTMASTER = "Flugmeister",
	LOGGING_VENDOR = "Händler",
	LOGGING_TRAINER = "Trainer",
	LOGGING_REPAIR = "Reparatur",
	LOGGING_OWN_GOLD = "Eigenes Gold",
	LOGGING_GUILD = "Gilde",
	LOGGING_AUTOSELL = "Auto Sell Junk",
	LOGGING_COSTS = "Kosten",
	LOGGING_SALE_TO = "Verkauf an %s",
	LOGGING_ITEM = "Item",
	LOGGING_ITEMS = "Items",
	LOGGING_REPAIRS = "Reparaturen",
	LOGGING_SELF_PAID = "Selbst bezahlt",
	LOGGING_ENTRY = "Eintrag",
	ITEMS_LABEL = "Items",
	PET_STUFF_TITLE = "Pet Stuff",
	SEASON_NAME_MIDNIGHT = "Midnight",
	CHECKLIST_DESC = "Hier hast du eine kleine To-Do-Zentrale für Daily, Weekly und Im Blick halten, ergänzt um manuelle Einträge und ein frei stehendes Tracker-Fenster für den Spielalltag.",
	CHECKLIST_SUMMARY = "%d / %d erledigt",
	CHECKLIST_INTRO_SUMMARY_DEFAULT = "0 / 0 erledigt",
	CHECKLIST_INTRO_HINT = "Die vorgegebenen Aufgaben sind bereits einsortiert. Eigene Aufgaben kannst du darunter als Daily oder Weekly ergänzen.",
	CHECKLIST_WATCH = "Im Blick halten",
	CHECKLIST_WATCH_SHORT = "Im Blick",
	CHECKLIST_WATCH_HINT = "Langfristige Punkte ohne automatischen Reset, die du einfach im Auge behalten möchtest.",
	CHECKLIST_EMPTY_WATCH = "Aktuell keine Aufgaben in dieser Kategorie vorhanden.",
	CHECKLIST_DAILY_HINT = "Alle Aufgaben, die sich beim täglichen EU-Reset zurücksetzen. Vorgegebene Aufgaben können rechts deaktiviert werden.",
	CHECKLIST_EMPTY_DAILY = "Aktuell keine Daily-Aufgaben vorhanden.",
	CHECKLIST_WEEKLY_HINT = "Alle Aufgaben, die sich beim wöchentlichen EU-Reset zurücksetzen.",
	CHECKLIST_EMPTY_WEEKLY = "Aktuell keine Weekly-Aufgaben vorhanden.",
	CHECKLIST_MANUAL_ADD_TITLE = "Manuelle Aufgabe hinzufügen",
	CHECKLIST_MANUAL_ADD_HINT = "Neue manuelle Aufgaben landen je nach Auswahl in Daily, Weekly oder Im Blick halten. Daily und Weekly resetten automatisch, Im Blick halten bleibt bestehen.",
	CHECKLIST_MANUAL_ADD_LABEL = "Neue manuelle Aufgabe",
	CHECKLIST_MANUAL_CATEGORY_HINT = "Typ beim Anlegen auswählen. In der Liste kannst du manuelle Aufgaben später zwischen allen drei Kategorien verschieben.",
	CHECKLIST_APPEARANCE = "Anzeige und Optik",
	CHECKLIST_APPEARANCE_HINT = "Das kleine Tracker-Fenster ist transparent, scrollbar und unten rechts größenverstellbar. Ziehen kannst du es an der Kopfzeile.",
	CHECKLIST_SHOW_TRACKER = "Tracker-Fenster anzeigen",
	CHECKLIST_SHOW_TRACKER_HINT = "Blendet außerhalb des Hauptfensters ein kleines Checklisten-Fenster ein.",
	CHECKLIST_SHOW_BUILTIN = "Vorgegebene Aufgaben im Tracker zeigen",
	CHECKLIST_SHOW_BUILTIN_HINT = "Zeigt die feste Starterliste auch im kleinen Tracker-Fenster an.",
	CHECKLIST_SHOW_MANUAL = "Manuelle Aufgaben im Tracker zeigen",
	CHECKLIST_SHOW_MANUAL_HINT = "Zeigt deine eigenen Aufgaben ebenfalls im kleinen Tracker-Fenster an.",
	CHECKLIST_HIDE_COMPLETED = "Erledigte To-Dos im Tracker ausblenden",
	CHECKLIST_HIDE_COMPLETED_HINT = "Praktisch für eine ruhigere Ingame-Ansicht, wenn nur offene Aufgaben sichtbar sein sollen.",
	CHECKLIST_TRACKER_FONT_SIZE = "Schriftgröße im Tracker",
	CHECKLIST_RESET_CHECKS = "Alle Haken zurücksetzen",
	CHECKLIST_RESET_BUILTIN = "Vorgegebene zurücksetzen",
	CHECKLIST_RESET_TRACKER = "Tracker-Fenster zurücksetzen",
	CHECKLIST_TRACKER_EMPTY_OPEN = "Keine To-Dos für den Tracker sichtbar.",
	CHECKLIST_TRACKER_EMPTY_HIDDEN = "Keine offenen To-Dos für den Tracker sichtbar.",
	CHECKLIST_TRACKER_TITLE = "Checkliste %d/%d",
	CHECKLIST_TRACKER_LOCKED = "Tracker fixiert",
	CHECKLIST_TRACKER_LOCKED_HINT = "Ziehen und Größenänderung sind gesperrt. Klick zum Lösen.",
	CHECKLIST_TRACKER_UNLOCKED = "Tracker frei",
	CHECKLIST_TRACKER_UNLOCKED_HINT = "Ziehen und Größenänderung sind möglich. Klick zum Fixieren.",
	CHECKLIST_SETTINGS_BUTTON = "Einst.",
	CHECKLIST_SETTINGS_TOOLTIP = "Checklisten-Einstellungen",
	CHECKLIST_SETTINGS_TOOLTIP_HINT = "Öffnet die Checklisten-Seite direkt beim Einstellungsblock.",
	CHECKLIST_ADD_BUTTON = "Add",
	CHECKLIST_ADD_TOOLTIP = "Aufgabe hinzufügen",
	CHECKLIST_ADD_TOOLTIP_HINT = "Öffnet ein kleines Fenster, um schnell eine manuelle Aufgabe anzulegen.",
	CHECKLIST_VAULT_TOOLTIP = "Weekly Vault",
	CHECKLIST_VAULT_TOOLTIP_HINT = "Öffnet oder schließt das Weekly-Rewards-Fenster.",
	CHECKLIST_VAULT_ERROR = "Beavis QoL: Das Vault-Fenster konnte gerade nicht geöffnet werden.",
	CHECKLIST_EXPAND = "Tracker ausklappen",
	CHECKLIST_EXPAND_HINT = "Zeigt die komplette Checkliste wieder an.",
	CHECKLIST_COLLAPSE = "Tracker einklappen",
	CHECKLIST_COLLAPSE_HINT = "Blendet die Checkliste aus und lässt nur den Header sichtbar.",
	CHECKLIST_CLOSE = "Tracker schließen",
	CHECKLIST_CLOSE_HINT = "Blendet das Tracker-Fenster aus. Über die Einstellungen kannst du es wieder einblenden.",
	CHECKLIST_NEW_TASK = "Neue Aufgabe",
	CHECKLIST_NEW_TASK_HINT = "Manuelle Aufgabe direkt im Tracker anlegen.",
	ADD_SHORT = "Hinzuf.",
	ADD = "Hinzufügen",
	FIX = "Fix",
	UNLOCK = "Lösen",
	CHECKLIST_TODO_WEEKLY_VAULT = "+10 oder höher für die Weekly Vault",
	CHECKLIST_TODO_WEEKLY_RAID = "Raid für Vault und BiS-Items",
	CHECKLIST_TODO_WEEKLY_PVP_QUESTS = "Wöchentliche PvP-Quests",
	CHECKLIST_TODO_WEEKLY_HUNTS = "Jagden für Wochenbelohnungen",
	CHECKLIST_TODO_WEEKLY_SOIREE = "Soiree für Wochenbelohnungen",
	CHECKLIST_TODO_WEEKLY_OVERFLOW = "Überfluss für Wochenbelohnungen",
	CHECKLIST_TODO_WEEKLY_STORMARION = "Sturmarion-Angriff für Wochenbelohnungen",
	CHECKLIST_TODO_WEEKLY_HARANDIR = "Harandir-Event für Wochenbelohnungen",
	CHECKLIST_TODO_WEEKLY_VOIDSTORM = "Leerensturm: 3 Weltquests für Rüstmeister-Belohnung",
	CHECKLIST_TODO_WEEKLY_DELVE_PROGRESS = "Wöchentlicher Tiefenfortschritt",
	CHECKLIST_TODO_WEEKLY_DELVE_HERO_MAP = "Wöchentliche Tiefen-Held-Karte",
	CHECKLIST_TODO_DAILY_DELVES = "4 Aufgestiegene Tiefen für tägliche Belohnungen",
	CHECKLIST_TODO_DAILY_WORLDQUESTS = "Weltquests für Ruf und Währungen",
	CHECKLIST_TODO_DAILY_M0 = "M0 World Tour für zusätzliche Beute",
	CHECKLIST_TODO_DAILY_HARANDIR = "Harandir-Tagesquest für täglichen Fortschritt",
	CHECKLIST_TODO_WATCH_TIER = "4er-Set-Fortschritt",
	CHECKLIST_TODO_WEEKLY_PROFESSION = "Max. Wöchentliche Berufspunkte farmen (%s)",
}
