local _, BeavisQoL = ...

BeavisQoL = BeavisQoL or {}
BeavisQoL.Localization = BeavisQoL.Localization or {}

BeavisQoL.Localization.enUS = {
	-- General
	UNKNOWN = "Unknown",
	RELOAD = "Reload",
	CLOSE = "Close",
	CANCEL = "Cancel",
	VERSION = "Version",
	LANGUAGE = "Language",

	-- Header/Main
	HEADER_SUBTITLE = "QoL hub for progress, comfort and interface",

	-- Navigation
	NAVIGATION = "Navigation",
	NAVIGATION_HINT = "",
	NAVIGATION_SEARCH_PLACEHOLDER = "Search navigation",
	NAVIGATION_SEARCH_HINT = "Filters names and page text live.",
	NAVIGATION_SEARCH_RESULTS = "%d matches in navigation",
	NAVIGATION_SEARCH_EMPTY = "No matches in navigation.",
	NAVIGATION_SECTION_ADDON = "Addon",
	GENERAL = "General",
	MODULES = "Modules",
	HOME = "Home",
	SETTINGS = "Settings",
	GOLDAUSWERTUNG = "Gold Log",
	GOLD_TRADE = "Gold & Trade",
	GOLDAUSWERTUNG_DESC = "Compact overview for income, expenses, repairs and currencies. Full history is available via History.",
	INTERFACE_COMBAT = "Interface & Combat",
	GOLDAUSWERTUNG_CLEANUP = "Clear period",
	STREAMER_TOOLS = "Streamer Tools",
	PROGRESS_QUESTS = "Progress & Quests",
	GOLD_VENDOR = "Gold & Vendors",
	EVERYDAY_AUTOMATION = "Everyday & Automation",
	WINDOWS_SEARCH = "Windows & Search",
	WORLD_TRAVEL = "World & Travel",
	GROUP_INSTANCES = "Group & Instances",
	INTERFACE_OVERLAYS = "Interface & Overlays",
	GOLDAUSWERTUNG_RETENTION_HINT = "Repairs 30 days, gold and currencies 1 year.",

	GOLDAUSWERTUNG_CLEANUP_TITLE = "Clear log period",
	LEVEL_TIME = "Level Time",
	GOLDAUSWERTUNG_CLEANUP_HINT = "Removes entries older than the selected period. Repairs are always limited to 30 days.",
	WEEKLY_KEYS = "Weekly Keys",
	GOLDAUSWERTUNG_HISTORY_TITLE = "Full history",
	QUEST_CHECK = "Quest Check",
	GOLDAUSWERTUNG_HISTORY_HINT = "Search or switch between categories.",
	LOGGING = "Logging",
	GOLDAUSWERTUNG_HISTORY_TAB_INCOME = "Income",
	AUTOREPAIR = "Auto Repair",
	AUCTION_HOUSE_MODULE = "Auction House",
	GOLDAUSWERTUNG_HISTORY_TAB_EXPENSE = "Expenses",
	EASY_DELETE = "Easy Delete",
	TOOLTIP_ITEMLEVEL = "Tooltip-Itemlevel",
	TOOLTIP_SETTINGS = "Tooltip Settings",
	GOLDAUSWERTUNG_HISTORY_TAB_REPAIRS = "Repairs",
	CAMERA_DISTANCE = "Camera Distance",
	MACRO_FRAME = "Macro Window",
	TALENT_FRAME_SCALE = "Talent Window Scale",
	GOLDAUSWERTUNG_HISTORY_TAB_CURRENCY = "Currencies",
	FISHING_HELPER = "Easy Fishing",
	GOLDAUSWERTUNG_HISTORY_SEARCH = "Search",
	MARKER_BAR = "Marker Bar",
	GOLDAUSWERTUNG_HISTORY_LOAD_MORE = "Load more",
	MOUSE_HELPER = "Mouse Helper",
	MINIMAP_COLLECTOR = "Minimap Collector",
	GOLDAUSWERTUNG_HISTORY_NO_MATCHES = "No matches in current history.",
	LFG = "Group Finder",
	GOLDAUSWERTUNG_OVERVIEW_NO_MATCHES = "No matches for this search.",
	PET_STUFF = "Pet Stuff",
	MODULE_OVERVIEW = "Overview",
	GOLDAUSWERTUNG_HISTORY_SHOWING = "%d entries visible.",
	-- Settings
	GOLDAUSWERTUNG_HISTORY_SHOWING_MORE = "%d entries visible. More entries can be loaded.",
	GLOBAL_SETTINGS_DESC = "Here you can adjust settings for the entire addon window and the minimap button.",
	GOLDAUSWERTUNG_ENTRY = "Entry",
	SETTINGS_SECTION_GENERAL_DESC = "Language and main window behavior belong together, so they are grouped at the top.",
	GOLDAUSWERTUNG_MISC = "Miscellaneous",
	SETTINGS_SECTION_MINIMAP_DESC = "Minimap icon options stay in their own block instead of being mixed into the rest of the interface.",
	GOLDAUSWERTUNG_SALE = "Sale",
	SETTINGS_SECTION_QUICK_HIDE_DESC = "Choose which overlays should be hidden automatically in instanced areas and whether that should only happen in combat.",
	GOLDAUSWERTUNG_ITEM = "Item",
	SETTINGS_SECTION_RESET_DESC = "Rare recovery actions are separated so they do not get lost between normal options.",
	GOLDAUSWERTUNG_ITEMS = "Items",
	MINIMAP_BUTTON_HIDE = "Hide Minimap Button",
	GOLDAUSWERTUNG_REPAIR = "Repair",
	QUICK_HIDE_CHECKLIST_OVERLAY = "Hide checklist overlay",
	GOLDAUSWERTUNG_REPAIRS = "Repairs",
	QUICK_HIDE_STATS_OVERLAY = "Hide stats overlay",
	GOLDAUSWERTUNG_SELF_PAID = "Self paid",
	HIDE_OVERLAYS_IN_COMBAT = "Hide overlays in instance combat",
	GOLDAUSWERTUNG_GUILD = "Guild",

	GOLDAUSWERTUNG_VENDOR = "Vendor",
	WELCOME_TITLE = "Everything Important at a Glance",
	GOLDAUSWERTUNG_VENDOR_SALE = "Vendor",
	WELCOME_SUBTITLE = "",
	WELCOME_BODY = "Choose a category on the left and open the modules you need directly.",
	GOLDAUSWERTUNG_MAIL = "Mail",
	HOME_SUPPORT_TITLE = "Support Me",
	RELEASE_STATUS_FORMAT = "Status: %s",
	HOME_SUPPORT_BODY = "This project takes a lot of time.",
	GOLDAUSWERTUNG_MAILBOX = "Mailbox",
	HOME_SUPPORT_HINT = "You can support me on Twitch or directly with a donation.",
	HOME_SUPPORT_LINK = "Open donation link",
	HOME_SUPPORT_POPUP = "Open donation link",
	RELEASE_CHANNEL_BETA = "Beta",
	GOLDAUSWERTUNG_AUCTIONHOUSE = "Auction House",
	RELEASE_CHANNEL_RELEASE = "Release",
	GOLDAUSWERTUNG_TRADE = "Trade",
	STATUS_FOCUS = "Focus: stable core modules, clear controls and compact access to frequently used features.",
	GOLDAUSWERTUNG_QUEST = "Quest",
	PROGRESS_CARD_TITLE = "Progress at a Glance",
	GOLDAUSWERTUNG_QUEST_REWARD = "Quest reward",
	PROGRESS_CARD_FOOTER = "Level Time - Checklist - Weekly Keys - Itemlevel Guide - Quest Check",
	GOLDAUSWERTUNG_LOOT = "Loot",
	COMFORT_CARD_TITLE = "Less Busywork",
	GOLDAUSWERTUNG_PICKED_UP = "Picked up",
	COMFORT_CARD_FOOTER = "Auto Sell - Auto Repair - Fast Loot - Easy Delete - Camera Distance",
	GOLDAUSWERTUNG_FLIGHTMASTER = "Flight Master",
	TWITCH_TITLE = "Twitch",
	GOLDAUSWERTUNG_TRAINER = "Trainer",
	TWITCH_FOOTER = "To the Twitch channel",
	TWITCH_POPUP = "Open Twitch channel",

	DISCORD_TITLE = "Discord & Support",
	DISCORD_BODY = "Feedback, ideas and support are handled through the website and community channels so open points can be tracked in one place.",
	DISCORD_FOOTER = "To the Beavismania website",
	DISCORD_POPUP = "Open Beavismania",
	HOME_FEEDBACK_TITLE = "Feedback, Ideas & Bugs",
	HOME_FEEDBACK_BODY = "Feedback, ideas and bug reports are handled through the website.",
	HOME_FEEDBACK_FOOTER = "To the Beavismania website",
	HOME_FEEDBACK_POPUP = "Open Beavismania",
	WEBSITE_CARD_TITLE = "Beavismania.de",
	WEBSITE_CARD_BODY = "Find all information about the stream, guides, addons, and every past stream to rewatch in one place at www.beavismania.de.",
	WEBSITE_CARD_FOOTER = "Go to www.beavismania.de",
	WEBSITE_CARD_POPUP = "Open Beavismania.de",

	FOOTER_TEXT = "The interface is designed for short paths, clear sections and enough room for additional modules.",

	-- Link Popup
	LINK_OPEN = "Open link",
	LINK_COPY_DESC = "World of Warcraft does not allow addons to open websites directly. You can highlight and copy the address here:",
	LINK_COPY_HINT = "Tip: Highlight the link and copy with Ctrl+C.",
	MINIMAP_TRACKER_SHOW = "Show checklist tracker",
	MINIMAP_WEEKLY_KEYS_SHOW = "Show weekly keys",
	MINIMAP_STATS_SHOW = "Show stats",
	MINIMAP_MARKER_BAR_SHOW = "Show marker bar",
	MINIMAP_STREAMER_PLANNER_SHOW = "Show group planner",
	MINIMAP_EASY_LFG_SHOW = "Show Easy LFG",
	MINIMAP_PORTAL_VIEWER_SHOW = "Show Season Portals",
	MINIMAP_QUICK_HIDE_SHOW = "Auto-hide windows",
	MINIMAP_QUICK_HIDE_SETTINGS = "Settings",
	MINIMAP_CONTEXT_MENU_ENTRY_VISIBLE = "Show entry in minimap quick menu",
	MINIMAP_CONTEXT_MENU_ENTRY_VISIBLE_HINT = "Controls whether this module appears in the minimap button quick menu.",
	MINIMAP_CONTEXT_QUICK_VIEW = "Quick View",
	MINIMAP_CONTEXT_TOGGLE_SECTION = "On/Off",
	MINIMAP_LEFT_CLICK = "Left-click: Open / close window",
	MINIMAP_RIGHT_CLICK = "Right-click: Quick menu",
	MINIMAP_SHIFT_CLICK = "Shift-click: Reload UI",
	MINIMAP_DRAG = "Drag: Change position",
	ACTIVE = "Active",
	FONT = "Font",
	DISPLAY = "Display",
	IMPORTANT = "Important",
	READY = "Ready",
	NOT_FOUND = "Not found",
	STATUS = "Status",
	ADDON_MESSAGE = "Beavis QoL: %s",
	CHONKY_LOADOUT_LABEL = "Loadout",
	CHONKY_LOADOUT_TOOLTIP = "Select a talent loadout for the active specialization.",
	CHONKY_LOADOUT_NONE = "No loadout",
	CHONKY_LOADOUT_NO_LOADOUTS = "No loadouts",
	CHONKY_LOADOUT_FALLBACK_NAME = "Loadout %d",
	CHONKY_LOADOUT_COMBAT_BLOCKED = "Talent loadouts cannot be changed in combat.",
	CHONKY_LOADOUT_FAILED = "Could not switch loadout: %s",
	CHONKY_LOADOUT_API_MISSING = "Talent loadout API is not available.",
	CHONKY_LOADOUT_MENU_MISSING = "Dropdown menu API is not available.",
	PORTAL_VIEWER_TITLE = "Season Portals",
	PORTAL_VIEWER_DESC = "Quick overview of earned portals and direct use.",
	PORTAL_VIEWER_SUBTITLE = "Midnight S1 dungeon portals",
	PORTAL_VIEWER_HINT = "Shows which dungeon portals from the current Midnight Season 1 Mythic+ pool you already have and which are still missing.",
	PORTAL_VIEWER_SECTION_AVAILABLE = "Available",
	PORTAL_VIEWER_SECTION_MISSING = "Missing",
	PORTAL_VIEWER_EMPTY_AVAILABLE = "No Season 1 dungeon portal unlocked yet.",
	PORTAL_VIEWER_EMPTY_MISSING = "All Season 1 dungeon portals are available.",
	PORTAL_VIEWER_UNLOCKED = "Unlocked",
	PORTAL_VIEWER_LOCKED = "Missing",
	PORTAL_VIEWER_ACTION_USE = "Use",
	PORTAL_VIEWER_ACTION_MISSING = "Missing",
	PORTAL_VIEWER_CLICK_HINT = "Left-click: use portal",
	PORTAL_VIEWER_ACHIEVEMENT_UNKNOWN = "No matching portal achievement found",
	PORTAL_VIEWER_REQUIREMENT = "Unlock: Any portal reward for this dungeon",
	PORTAL_VIEWER_CLOSE_TOOLTIP = "Hide window",
	PORTAL_VIEWER_SETTINGS_HINT = "Configure the Season Portals window, its lock state and its quick-menu entry here.",
	PORTAL_VIEWER_ENABLE_WINDOW = "Enable Season Portals",
	PORTAL_VIEWER_ENABLE_WINDOW_HINT = "Toggles the Season Portals window and its functionality on or off.",
	PORTAL_VIEWER_LOCK_WINDOW = "Lock window",
	PORTAL_VIEWER_LOCK_WINDOW_HINT = "When enabled, the Portal Viewer window stays fixed in place and cannot be moved.",
	PORTAL_VIEWER_SHOW_MINIMAP_MENU = "Show in minimap quick menu",
	PORTAL_VIEWER_SHOW_MINIMAP_MENU_HINT = "Controls whether Season Portals appears in the minimap button quick menu.",
	PORTAL_VIEWER_DUNGEON_MAGISTERS_TERRACE = "Magisters' Terrace",
	PORTAL_VIEWER_DUNGEON_MAISARA_CAVERNS = "Maisara Caverns",
	PORTAL_VIEWER_DUNGEON_NEXUS_POINT_XENAS = "Nexus-Point Xenas",
	PORTAL_VIEWER_DUNGEON_WINDRUNNER_SPIRE = "Windrunner Spire",
	PORTAL_VIEWER_DUNGEON_ALGETHAR_ACADEMY = "Algeth'ar Academy",
	PORTAL_VIEWER_DUNGEON_PIT_OF_SARON = "Pit of Saron",
	PORTAL_VIEWER_DUNGEON_SEAT_OF_THE_TRIUMVIRATE = "Seat of the Triumvirate",
	PORTAL_VIEWER_DUNGEON_SKYREACH = "Skyreach",

	MISC_TITLE = "Comfort",
	MISC_DESC = "Here you will find comfort features that can be used independently of the rest of the addon.",
	REPUTATION_SEARCH = "Reputation Search",
	REPUTATION_SEARCH_PLACEHOLDER = "Search reputations",
	REPUTATION_SEARCH_HINT = "Adds a search box to Blizzard's reputation window so factions can be filtered directly.",
	CURRENCY_SEARCH = "Currency Search",
	CURRENCY_SEARCH_PLACEHOLDER = "Search currencies",
	CURRENCY_SEARCH_HINT = "Adds a search box to Blizzard's currency window so currencies can be filtered directly.",
	AUTOSELL_HINT = "Automatically sells all gray items with vendor value when you open a merchant.",
	AUTOREPAIR_HINT = "Automatically repairs damaged items when you open a merchant.",
	AUCTION_HOUSE_DESC = "Automates selected Blizzard auction house filters for expansion and rarity.",
	AUCTION_HOUSE_CURRENT_EXPANSION_FILTER = "Enable current expansion only automatically",
	AUCTION_HOUSE_CURRENT_EXPANSION_FILTER_HINT = "Automatically enables Blizzard's \"Current Expansion Only\" filter when the auction house opens.",
	AUCTION_HOUSE_POOR_QUALITY_FILTER = "Automatically disable Poor",
	AUCTION_HOUSE_POOR_QUALITY_FILTER_HINT = "Automatically disables Blizzard's \"Poor\" rarity filter in the auction house.",
	AUCTION_HOUSE_COMMON_QUALITY_FILTER = "Automatically disable Common",
	AUCTION_HOUSE_COMMON_QUALITY_FILTER_HINT = "Automatically disables Blizzard's \"Common\" rarity filter in the auction house.",
	AUCTION_HOUSE_FAVORITE_GROUPS_TITLE = "Favorite Groups",
	AUCTION_HOUSE_FAVORITE_GROUP_ALL = "All Favorites",
	AUCTION_HOUSE_FAVORITE_GROUP_UNGROUPED = "No Category",
	AUCTION_HOUSE_FAVORITE_GROUP_ADD_TOOLTIP = "Create a new favorite group",
	AUCTION_HOUSE_FAVORITE_GROUP_ASSIGN_TOOLTIP = "Assign this favorite to a group",
	AUCTION_HOUSE_FAVORITE_GROUP_CURRENT_LABEL = "Current group: %s",
	AUCTION_HOUSE_FAVORITE_GROUP_CURRENT_NONE = "Current group: None",
	AUCTION_HOUSE_FAVORITE_GROUP_EDIT_BUTTON = "Edit",
	AUCTION_HOUSE_FAVORITE_GROUP_EDIT_TOOLTIP = "Edit group",
	AUCTION_HOUSE_FAVORITE_GROUP_DELETE_TOOLTIP = "Delete group \"%s\"",
	AUCTION_HOUSE_FAVORITE_GROUP_CREATE_POPUP = "Name for the new favorite group:",
	AUCTION_HOUSE_FAVORITE_GROUP_RENAME_POPUP = "New name for the favorite group:",
	AUCTION_HOUSE_FAVORITE_GROUP_CREATE_BUTTON = "Create",
	AUCTION_HOUSE_FAVORITE_GROUP_CREATE_EMPTY = "Please enter a group name.",
	AUCTION_HOUSE_FAVORITE_GROUP_CREATE_DUPLICATE = "That favorite group already exists.",
	AUCTION_HOUSE_FAVORITE_GROUP_DELETE_CONFIRM = "Do you really want to delete the group \"%s\"?",
	AUCTION_HOUSE_FAVORITE_GROUP_MENU_TITLE = "Assign to group",
	AUCTION_HOUSE_FAVORITE_GROUP_MENU_CREATE = "Create new group",
	AUTOREPAIR_GUILD = "Prefer guild funds",
	AUTOREPAIR_GUILD_HINT = "If possible, guild gold will be used first for repairs.",
	EASY_DELETE_HINT = "Removes the text input for items with a DELETE confirmation and replaces it with a simple confirmation.",
	FAST_LOOT_HINT = "Loots directly on opening and hides the loot window in the process.",
	CUTSCENE_SKIP = "Cutscene Skip",
	CUTSCENE_SKIP_HINT = "Shows cutscenes and movies normally the first time they trigger. Once the same event key has been seen before, it will be skipped automatically on the next start.",
	FLIGHT_MASTER_TIMER = "Flight Master Timer",
	FLIGHT_MASTER_TIMER_HINT = "Shows a centered countdown during flight master travel and automatically learns missing route times over time.",
	FLIGHT_MASTER_TIMER_UNKNOWN = "Arrival unknown",
	FLIGHT_MASTER_TIMER_SOUND = "Arrival sound enabled",
	FLIGHT_MASTER_TIMER_SOUND_HINT = "Plays a short signal once when your flight ends. The selection uses Blizzard client sounds and does not bundle third-party audio files.",
	FLIGHT_MASTER_TIMER_SOUND_SELECT = "Sound:",
	FLIGHT_MASTER_TIMER_SOUND_TEST = "Test",
	FLIGHT_MASTER_TIMER_SOUND_PLAY_HINT = "Plays the currently selected sound once.",
	FLIGHT_MASTER_TIMER_SOUND_SQUIRE_HORN = "Squire Horn",
	FLIGHT_MASTER_TIMER_SOUND_DWARF_HORN = "Dwarf Horn",
	FLIGHT_MASTER_TIMER_SOUND_SIMON_CHIME = "Simon Chime",
	FLIGHT_MASTER_TIMER_SOUND_SCOURGE_HORN = "Scourge Horn",
	FLIGHT_MASTER_TIMER_SOUND_GRIMRAIL_TRAIN_HORN = "Grimrail Train Horn",
	FLIGHT_MASTER_TIMER_LOCK_OVERLAY = "Lock timer overlay",
	FLIGHT_MASTER_TIMER_LOCK_OVERLAY_HINT = "When unlocked, you can drag the timer overlay directly with left click during a flight. It stays locked by default.",
	FLIGHT_MASTER_TIMER_POSITION_MODE = "Position overlay",
	FLIGHT_MASTER_TIMER_POSITION_MODE_STOP = "Finish positioning",
	FLIGHT_MASTER_TIMER_POSITION_MODE_HINT = "Shows a sample overlay so you can move the timer even without an active flight and lock it again right away.",
	FLIGHT_MASTER_TIMER_PREVIEW_DESTINATION = "Dornogal",
	FLIGHT_MASTER_TIMER_RESET_HINT = "Moves the timer overlay back to its default position below the center of the screen.",
	TOOLTIP_ITEMLEVEL_HINT = "Shows the equipped item level of other players in the mouseover tooltip. Works via inspect and therefore only within range.",
	TOOLTIP_ITEMLEVEL_LABEL = "Item Level",
	TOOLTIP_ITEMLEVEL_LOADING = "checking...",
	MACRO_FRAME_HINT = "Expands Blizzard's macro window downward so more macros are visible at the same time.",
	TALENT_FRAME_SCALE_HINT = "Enables scaling for Blizzard's talent window. You can adjust the value directly here or later through the small percent button on the talent window.",
	TALENT_FRAME_SCALE_BUTTON_TOOLTIP = "Scale talent window",
	TALENT_FRAME_SCALE_BUTTON_TOOLTIP_HINT = "Opens a separate scaling window. It also lets you lock or unlock the talent window for dragging.",
	TALENT_FRAME_SCALE_WINDOW_LOCK_TOOLTIP = "Lock talent window",
	TALENT_FRAME_SCALE_WINDOW_UNLOCK_TOOLTIP = "Unlock talent window",
	TALENT_FRAME_SCALE_WINDOW_LOCK_TOOLTIP_HINT = "When unlocked, you can drag the talent window directly by its top bar and the position will be saved.",
	PREY_HUNT_PROGRESS_HINT = "Shows the current Midnight hunt stage directly on Blizzard's hunt symbol.",
	PREY_HUNT_STAGE_FORMAT = "Phase %d/%d",
	PREY_HUNT_STAGE_READY = "Boss ready",
	KEYSTONE_ACTIONS = "M+ Options",
	KEYSTONE_ACTIONS_HINT = "Replaces the activate button in the Mythic+ keystone window with Ready Check, Start and Timer Start. With Auto Timer enabled, Timer Start begins automatically once everyone is ready after your ready check.",
	KEYSTONE_ACTIONS_GROUP_LOCK = "Buttons only active in group",
	KEYSTONE_ACTIONS_GROUP_LOCK_HINT = "When enabled, Ready Check, Start and Timer Start stay locked outside a group.",
	KEYSTONE_ACTIONS_SECONDS = "Timer seconds:",
	KEYSTONE_ACTIONS_SECONDS_HINT = "Applies to Timer Start and Auto Timer. Allowed range is 1 to 30 seconds.",
	KEYSTONE_ACTIONS_AUTOTIMER = "Auto Timer",
	KEYSTONE_ACTIONS_READYCHECK = "Ready Check",
	KEYSTONE_ACTIONS_START = "Start",
	KEYSTONE_ACTIONS_PULLTIMER = "Timer Start",
	KEYSTONE_ACTIONS_CANCEL = "Cancel",
	FISHING_HELPER_DESC = "A one-key helper for relaxed fishing. The same key casts your line and, while your bobber is active, is temporarily remapped to Blizzard interaction so you can loot it with that same key without exact mouseover.",
	FISHING_HELPER_USAGE_HINT = "Flow: press the key to cast, keep the bobber in view, then press the same key again. While the bobber is in the water, your key stays on interaction instead of recasting.",
	FISHING_HELPER_ENABLE = "Enable Fishing Helper",
	FISHING_HELPER_SET_KEY = "Set key",
	FISHING_HELPER_CLEAR_KEY = "Clear key",
	FISHING_HELPER_CURRENT_KEY = "Current key",
	FISHING_HELPER_NO_KEY = "No key assigned",
	FISHING_HELPER_CAPTURE_HINT = "Press the key you want to use now. Escape cancels, Delete clears the binding.",
	FISHING_HELPER_STATUS = "Status",
	FISHING_HELPER_STATUS_DISABLED = "Disabled",
	FISHING_HELPER_STATUS_IDLE = "Ready to cast",
	FISHING_HELPER_STATUS_WAITING = "Bobber is out - waiting for a bite",
	FISHING_HELPER_STATUS_READY = "Bite detected - your key now triggers interaction",
	FISHING_HELPER_STATUS_NO_SPELL = "Fishing not found",
	FISHING_HELPER_STATUS_CAPTURE = "Waiting for key input",
	FISHING_HELPER_INTERACT_BINDING = "Blizzard interaction",
	FISHING_HELPER_INTERACT_BINDING_NONE = "No default key bound",
	FISHING_HELPER_INTERACT_HINT = "As soon as the bobber is active, your configured key is temporarily remapped to Blizzard interaction. The module also sets Soft Interact to the required value during that time so directional pickup can work reliably.",
	FISHING_HELPER_SOUND_ENABLE = "Highlight fishing sound",
	FISHING_HELPER_SOUND_MIN = "Fishing sound boost",
	FISHING_HELPER_SOUND_HINT = "While your bobber is out, the addon lowers music, ambience and pet sounds, boosts SFX and master volume relative to your current mix, and restores everything afterwards. 100% keeps your current level, 200% doubles it up to WoW's limit.",
	MOUSE_HELPER_DESC = "Keeps mouse quality-of-life options on one page: visible cursor marker, movement trail and Blizzard cursor enlargement.",
	MOUSE_HELPER_SETTINGS = "General",
	MOUSE_HELPER_ENABLE = "Enable Mouse Helper",
	MOUSE_HELPER_CURSOR_SIZE = "Blizzard cursor size",
	MOUSE_HELPER_CURSOR_SIZE_DEFAULT = "Default",
	MOUSE_HELPER_CURSOR_SIZE_32 = "32x32",
	MOUSE_HELPER_CURSOR_SIZE_48 = "48x48",
	MOUSE_HELPER_CURSOR_SIZE_64 = "64x64",
	MOUSE_HELPER_CURSOR_SIZE_96 = "96x96",
	MOUSE_HELPER_CURSOR_SIZE_128 = "128x128",
	MOUSE_HELPER_BLIZZARD_CURSOR = "Use Blizzard large cursor",
	MOUSE_HELPER_BLIZZARD_CURSOR_HINT = "Toggles Blizzard's built-in large cursor setting directly from this module.",
	MOUSE_HELPER_BLIZZARD_CURSOR_UNSUPPORTED = "No supported Blizzard cursor-size CVar was detected on this client.",
	MINIMAP_COLLECTOR_DESC = "Collects detected addon minimap buttons into a separate movable launcher with an attached transparent button window.",
	MINIMAP_COLLECTOR_ENABLE = "Enable minimap collector",
	MINIMAP_COLLECTOR_ENABLE_HINT = "Shows or hides the separate collector launcher. When disabled, all buttons stay at their normal minimap positions.",
	MINIMAP_COLLECTOR_LAUNCHER_DESC = "The collector uses its own launcher on the screen. Left-click opens the attached window, Shift-left-click reloads the UI, right-click opens /beavis, and dragging repositions the launcher.",
	MINIMAP_COLLECTOR_SCALE = "Scale",
	MINIMAP_COLLECTOR_SCALE_HINT = "Adjusts the launcher and collector window size together.",
	MINIMAP_COLLECTOR_LAUNCHER_SCALE = "Button scale",
	MINIMAP_COLLECTOR_LAUNCHER_SCALE_HINT = "Adjusts only the movable launcher button size.",
	MINIMAP_COLLECTOR_WINDOW_SCALE = "Window scale",
	MINIMAP_COLLECTOR_WINDOW_SCALE_HINT = "Adjusts only the collector window size.",
	MINIMAP_COLLECTOR_BUTTONS_DESC = "Choose whether detected minimap buttons should be collected, left on the minimap, or fully hidden.",
	MINIMAP_COLLECTOR_BUTTONS_HINT = "Move addons between collector, minimap, and hidden with drag and drop.",
	MINIMAP_COLLECTOR_COLUMN_COLLECT = "Collect in button collector",
	MINIMAP_COLLECTOR_COLUMN_VISIBLE = "Keep on minimap",
	MINIMAP_COLLECTOR_COLUMN_HIDE = "Hide",
	MINIMAP_COLLECTOR_COLUMN_EMPTY = "No addons in this column.",
	MINIMAP_COLLECTOR_SELECTED = "Selected: %s",
	MINIMAP_COLLECTOR_SELECTED_NONE = "No addon selected.",
	MINIMAP_COLLECTOR_MOVE_LEFT = "Move left",
	MINIMAP_COLLECTOR_MOVE_RIGHT = "Move right",
	MINIMAP_COLLECTOR_EMPTY = "No collectible minimap buttons have been detected yet.",
	MINIMAP_COLLECTOR_RESET_POSITION = "Reset launcher position",
	MINIMAP_COLLECTOR_LAUNCHER_CLICK = "Left-click: Open / close collector window",
	MINIMAP_COLLECTOR_LAUNCHER_RELOAD = "Shift-left-click: Reload UI",
	MINIMAP_COLLECTOR_LAUNCHER_MENU = "Right-click: Open /beavis",
	MINIMAP_COLLECTOR_LAUNCHER_DRAG = "Drag: Move launcher",
	MINIMAP_COLLECTOR_MODE_COLLECT = "Collect",
	MINIMAP_COLLECTOR_MODE_SHOW = "Minimap",
	MINIMAP_COLLECTOR_MODE_HIDE = "Hide",
	MOUSE_HELPER_CIRCLE_TITLE = "Cursor Circle",
	MOUSE_HELPER_CIRCLE_ENABLE = "Show circle",
	MOUSE_HELPER_CIRCLE_COMBAT_ONLY = "Show circle only in combat",
	MOUSE_HELPER_CIRCLE_CLASS_COLOR = "Use class color automatically",
	MOUSE_HELPER_CAST_RING_ENABLE = "Show cast ring while casting",
	MOUSE_HELPER_CAST_RING_COLOR = "Cast ring color",
	MOUSE_HELPER_CIRCLE_SIZE = "Size",
	MOUSE_HELPER_CIRCLE_THICKNESS = "Border thickness",
	MOUSE_HELPER_CIRCLE_SHAPE = "Shape",
	MOUSE_HELPER_SHAPE_RING = "Ring",
	MOUSE_HELPER_SHAPE_SQUARE = "Square",
	MOUSE_HELPER_SHAPE_DIAMOND = "Diamond",
	MOUSE_HELPER_COLOR_PICK = "Pick color",
	MOUSE_HELPER_CIRCLE_HINT = "The circle follows your cursor in real time and stays centered around it.",
	MOUSE_HELPER_TRAIL_TITLE = "Mouse Trail",
	MOUSE_HELPER_TRAIL_ENABLE = "Show trail",
	MOUSE_HELPER_TRAIL_LENGTH = "Length",
	MOUSE_HELPER_TRAIL_SIZE = "Dot size",
	MOUSE_HELPER_TRAIL_STYLE = "Trail style",
	MOUSE_HELPER_TRAIL_CLASS_COLOR = "Use class color automatically",
	MOUSE_HELPER_TRAIL_STYLE_LIGHTNING = "Lightning",
	MOUSE_HELPER_TRAIL_STYLE_HOLY = "Holy Light",
	MOUSE_HELPER_TRAIL_STYLE_ARC = "Arc Ribbons",
	MOUSE_HELPER_TRAIL_STYLE_CLEAN = "Clean",
	MOUSE_HELPER_TRAIL_HINT = "Leaves short fading points behind your cursor while moving.",
	BOSS_GUIDES_DESC = "Shows a Boss Guides button at the top-left in supported dungeons/raids. It opens a window with boss tabs and stored tactics.",
	BOSS_GUIDES_SETTINGS = "Settings",
	BOSS_GUIDES_SHOW_OVERLAY = "Show overlay button",
	BOSS_GUIDES_OVERLAY_MODE = "Display mode",
	BOSS_GUIDES_MODE_ALWAYS = "Always show",
	BOSS_GUIDES_MODE_INSTANCE = "Only in dungeon/raid",
	BOSS_GUIDES_LOCK_OVERLAY = "Lock overlay position",
	BOSS_GUIDES_SCALE = "Scale",
	BOSS_GUIDES_FONT_SIZE = "Font Size",
	BOSS_GUIDES_RESET_POSITION = "Reset positions",
	BOSS_GUIDES_BUTTON = "Boss Guides",
	BOSS_GUIDES_OVERVIEW_TITLE = "Guide Overview",
	BOSS_GUIDES_OVERVIEW_HINT = "Pick a category or open a guide directly from the overview.",
	BOSS_GUIDES_EMPTY_CATEGORY = "No boss guide is available for this category yet.",
	BOSS_GUIDES_OPEN_GUIDE = "Open guide",
	BOSS_GUIDES_BOSS_COUNT = "%d bosses",
	BOSS_GUIDES_GUIDE_COUNT = "%d guides",
	BOSS_GUIDES_STATUS_ALWAYS = "Always visible",
	BOSS_GUIDES_STATUS_INSTANCE = "Only in instance",
	BOSS_GUIDES_STATUS_LOCKED = "Locked",
	BOSS_GUIDES_STATUS_UNLOCKED = "Movable",
	BOSS_GUIDES_BOSSES = "Bosses",
	BOSS_GUIDES_INSTANCE = "Instance",
	BOSS_GUIDES_NO_GUIDE = "No guide is currently available for this instance.",
	BOSS_GUIDES_CURRENT_INSTANCE = "Current instance",
	BOSS_GUIDES_NONE = "None",
	BOSS_GUIDES_CAT_RAID = "Raid",
	BOSS_GUIDES_CAT_DUNGEON = "Dungeon",
	BOSS_GUIDES_HOME_CATEGORY_RAIDS = "Raids",
	BOSS_GUIDES_HOME_CATEGORY_DUNGEONS = "Dungeons",
	BOSS_GUIDES_HOME_EMPTY = "No boss guides available yet.",
	BOSS_GUIDES_SELECT_INSTANCE = "Select instance...",
	BOSS_GUIDES_NO_INSTANCES = "No entries yet",
	BOSS_GUIDES_SECTION_GENERAL = "General",
	BOSS_GUIDES_LABEL_MYTHIC = "Mythic",
	BOSS_GUIDES_LEGEND_TANK = "Tank",
	BOSS_GUIDES_LEGEND_DD = "DPS",
	BOSS_GUIDES_LEGEND_HEAL = "Heal",
	BOSS_GUIDES_LEGEND_HC = "HC",
	BOSS_GUIDES_LEGEND_M = "M",
	BOSS_GUIDES_INSTANCE_VOIDSPIRE_TITLE = "Voidspire",
	BOSS_GUIDES_INSTANCE_VOIDSPIRE_TOKENS = { "voidspire", "void spire" },
	BOSS_GUIDES_BOSS_IMPERATOR_AVERZIAN_NAME = "Imperator Averzian",
	BOSS_GUIDES_BOSS_IMPERATOR_AVERZIAN_BODY = [=[
General: Control the 3x3 grid. Three connected lost tiles are wipe-threatening.
{TANK} Keep the boss off claimed tiles. Swap cleanly on Blackening Wounds. Take add waves from the Weakened target.
{DD} Place Umbral Collapse on key tiles or priority adds. Interrupt Voidshaper and Pitch Bulwark. Dodge Oblivion's Wrath, Void Fall and Shadow Phalanx.
{HEAL} Soak Umbral Collapse with the full group. Cover Dark Uproar and Void Infusion with CDs. Stabilize Dark Barrage targets fast.
{HC} Voidshapers turn into Endwalkers, so stop casts immediately. Prevent Voidmaws from healing on tiles at 35% and finish them.
{M} Prioritize Black Miasma curses. Remove Cosmic Shell before Umbral Collapse. Handle Void Marked with clean dispel positions.
]=],
	BOSS_GUIDES_BOSS_VORASIUS_NAME = "Vorasius",
	BOSS_GUIDES_BOSS_VORASIUS_BODY = [=[
General: Manage the arena actively. Break walls on purpose and never sweep breath through the raid.
{TANK} Stay in melee or Overpowering Pulse happens. Soak Shadowclaw Slash safely. Swap after Smashed or 2 heavy hits.
{DD} Kill Blistercreeps at the chosen wall. Move out 8 yards after Blisterburst. Dodge Void Breath and aftershocks.
{HEAL} Blisterburst and Primordial Roar are the main spikes. Plan for Creep Spit slows and knockbacks. Stagger CDs over the fight.
{HC} Walls need more explosions. Call add kills early and save space.
{M} Blisterburst leaves Dark Goo. Plan kill zones strictly and do not block the same path twice.
]=],
	BOSS_GUIDES_BOSS_FALLEN_KING_SALHADAAR_NAME = "Fallen King Salhadaar",
	BOSS_GUIDES_BOSS_FALLEN_KING_SALHADAAR_BODY = [=[
General: Orbs must never reach the boss. Every pass-through increases raid damage sharply.
{TANK} Move the boss out of orb lines and Torturous Extract. Place Shattering Twilight at the edge. Swap on Destabilizing Strikes.
{DD} Destroy Concentrated Void before it reaches the boss. Kick Fractured Images immediately. Use Entropic Unraveling as a burn window.
{HEAL} Cover Void Infusion, Twisting Obscurity and Entropic Unraveling with CDs. Keep Despotic Command targets out of the raid. Dispel Oppressive Darkness deliberately.
{HC} Stagger orb kills because Dark Radiation hits everyone. Spread marked Despotic Command players strictly.
{M} Enduring Void returns and must be planned for. Remove Nexus Shield on Images with a kick rotation. The fight is won on orb timing.
]=],
	BOSS_GUIDES_BOSS_VAELGOR_EZZORAK_NAME = "Vaelgor & Ezzorak",
	BOSS_GUIDES_BOSS_VAELGOR_EZZORAK_BODY = [=[
General: Keep the dragons apart and their health even. Otherwise Twilight Bond escalates.
{TANK} Maintain at least 15 yards of distance. Swap after Vaelwing and Rakfang. Turn Nullbeam, Gloom and Dread Breath away from the raid.
{DD} Control Gloom with fixed soakers. Break Nullzone only on purpose. Kick and kill Voidorbs immediately. Carry Shadowmark apart.
{HEAL} Plan Nullsnap, implosion and Midnight Flames as fixed CD windows. Track Gloomtouched and Nullbeam stacks actively.
{HC} Gloomtouched applies Diminish. Rotate soakers and avoid double contacts.
{M} Catch Nullscatter on the first snap. Prioritize Cosmosis reflections. Prepare for long Midnight Flames as the HPS check.
]=],
	BOSS_GUIDES_BOSS_LIGHTBLINDED_VANGUARD_NAME = "Lightblinded Vanguard",
	BOSS_GUIDES_BOSS_LIGHTBLINDED_VANGUARD_BODY = [=[
General: Keep health even and do not kill one boss early. Otherwise Retribution empowers the rest.
{TANK} Pull aura bosses away from the others. Pick up Lightblood and Bellamy cleanly after Judgment. Plan Exorcism chains and tank hits defensively.
{DD} Handle Execution Sentence only with the assigned soak group. Break Sacred Shield fast. Interrupt Blinding Light first and dodge charge and hammer.
{HEAL} Plan Light Infused and Searing Radiance early instead of reacting late. Call Tyr's Wrath targets to Senn. Cover Divine Toll plus Execution Sentence as a kill combo.
{HC} Consecration zones remain on the floor. Rotate bosses cleanly to the edge.
{M} Zealous Spirit empowers core abilities. Divine Consecration makes ground space deadly. Rotate defensive CDs per aura.
]=],
	BOSS_GUIDES_BOSS_CROWN_OF_COSMOS_NAME = "Crown of the Cosmos",
	BOSS_GUIDES_BOSS_CROWN_OF_COSMOS_BODY = [=[
General: This is a phase fight. Silver arrows cleanse void effects and solve many mechanics.
{TANK} Keep P1 Sentinels in melee so Echoing Darkness does not stack. Split Alleria and the Simulacrum in P2 to limit Empowering Darkness. Taunt Rift Slash regularly.
{DD} Aim Silverstrike through debuffs and adds. Control Sentinels and Droplets in P1. Break Cosmic Barrier instantly in P2 and kill Voidspawn before Coalesced Form. Dodge intermissions cleanly.
{HEAL} Dispel Null Corona in a controlled way. Biggest checks are Echoing Darkness, barrier aura, Voidstalker Sting and Devouring Cosmos. Save CDs for P3.
{HC} Void Expulsion hits extra targets. Use fixed Barrage calls in both intermissions.
{M} Use Silver Residue on Sentinels actively. Grasp of Emptiness and Barrage stacks punish mistakes hard. Clean arrow lines are mandatory.
]=],
	BOSS_GUIDES_INSTANCE_DREAMRIFT_TITLE = "Dreamrift",
	BOSS_GUIDES_INSTANCE_DREAMRIFT_TOKENS = { "dreamrift", "dream rift" },
	BOSS_GUIDES_BOSS_CHIMAERUS_NAME = "Chimaerus, the Undreamt God",
	BOSS_GUIDES_BOSS_CHIMAERUS_BODY = [=[
General: Realm management is everything. Free the adds first, then kill them fast and never let the boss consume them.
{TANK} Keep Rending Slash away from the raid. Rotate Upheaval with fixed groups. Pick up Colossal Horrors immediately and tank them defensively.
{DD} Break Alnshroud first in the rift. Prioritize Manifestations in reality. Kick Fearsome Cry and Essence Bolt. Fully dodge the flight phase and clear adds before Ravenous Dive.
{HEAL} Plan Rift Sickness as an absorb mechanic in advance. Cover Caustic Phlegm and Cannibalized Essence with CDs. Fixed soak groups keep damage predictable.
{HC} Dispel Consuming Miasma deliberately to clear Alndust Essence. Keep space clean for the whole fight.
{M} Rift Madness needs fixed realm-swap partners. Handle Dissonance with strict spacing. Prioritize the extra flight-phase adds immediately.
]=],
	BOSS_GUIDES_INSTANCE_MARCH_ON_QUEL_DANAS_TITLE = "March on Quel'Danas",
	BOSS_GUIDES_INSTANCE_MARCH_ON_QUEL_DANAS_TOKENS = { "march on quel danas", "march on queldanas", "march on quel'danas", "quel danas", "quel'danas" },
	BOSS_GUIDES_BOSS_BELOREN_CHILD_OF_ALAR_NAME = "Belo'ren, Child of Al'ar",
	BOSS_GUIDES_BOSS_BELOREN_CHILD_OF_ALAR_BODY = [=[
General: A void-twisted phoenix guards the path to the Sunwell. This boss is already listed in the guide, but the detailed tactic notes are still being prepared.
{TANK} No finalized tactic note is stored yet.
{DD} No finalized tactic note is stored yet.
{HEAL} No finalized tactic note is stored yet.
]=],
	BOSS_GUIDES_BOSS_MIDNIGHT_FALLS_NAME = "Midnight Falls",
	BOSS_GUIDES_BOSS_MIDNIGHT_FALLS_BODY = [=[
General: L'ura's unleashed void energy now threatens the Sunwell itself. This boss is already listed in the guide, but the detailed tactic notes are still being prepared.
{TANK} No finalized tactic note is stored yet.
{DD} No finalized tactic note is stored yet.
{HEAL} No finalized tactic note is stored yet.
]=],
	BOSS_GUIDES_INSTANCE_WINDRUNNER_SPIRE_TITLE = "Windrunner Spire",
	BOSS_GUIDES_INSTANCE_MAGISTERS_TERRACE_TITLE = "Magisters' Terrace",
	BOSS_GUIDES_INSTANCE_ALGETHAR_ACADEMY_TITLE = "Algeth'ar Academy",
	BOSS_GUIDES_INSTANCE_PIT_OF_SARON_TITLE = "Pit of Saron",
	BOSS_GUIDES_INSTANCE_MAISARA_CAVERNS_TITLE = "Maisara Caverns",
	BOSS_GUIDES_INSTANCE_SKYREACH_TITLE = "Skyreach",
	BOSS_GUIDES_INSTANCE_SEAT_OF_THE_TRIUMVIRATE_TITLE = "Seat of the Triumvirate",
	BOSS_GUIDES_INSTANCE_NEXUS_POINT_XENAS_TITLE = "Nexus-Point Xenas",
	BOSS_GUIDES_SPELL_NAMES = {
		["Shadow Phalanx"] = { spellID = 1284786, localizedName = "Shadow Phalanx" },
		["Dark Uproar"] = { spellID = 1249251, localizedName = "Dark Uproar" },
		["Blisterburst"] = { spellID = 1259186, localizedName = "Blisterburst" },
		["Void Breath"] = { spellID = 1256855, localizedName = "Void Breath" },
		["Void Convergence"] = { spellID = 1247738, localizedName = "Void Convergence" },
		["Entropic Unraveling"] = { spellID = 1246175, localizedName = "Entropic Unraveling" },
		["Dread Breath"] = { spellID = 1244221, localizedName = "Dread Breath" },
		["Gloom"] = { spellID = 1245391, localizedName = "Gloom" },
		["Twilight Bond"] = { spellID = 1270189, localizedName = "Twilight Bond" },
		["Radiant Barrier"] = { spellID = 1248847, localizedName = "Radiant Barrier" },
		["Nullbeam"] = { spellID = 1262623, localizedName = "Nullbeam" },
		["Execution Sentence"] = { spellID = 1248983, localizedName = "Execution Sentence" },
		["Aura of Wrath"] = { spellID = 1248449, localizedName = "Aura of Wrath" },
		["Aura of Devotion"] = { spellID = 1246162, localizedName = "Aura of Devotion" },
		["Aura of Peace"] = { spellID = 1248451, localizedName = "Aura of Peace" },
		["Judgment"] = { spellID = 1246736, localizedName = "Judgment" },
		["Umbral Collapse"] = "Umbral Collapse",
		["March of the Endless"] = "March of the Endless",
		["Echoing Darkness"] = { localizedName = "Echoing Darkness", tooltipKind = "Boss Mechanic", tooltipText = "Stage 1 sentinel aura. It ramps if the sentinels are not kept controlled in melee." },
		["Empowering Darkness"] = { localizedName = "Empowering Darkness", tooltipKind = "Boss Mechanic", tooltipText = "Stage 2 buff. It builds when the Simulacrum is kept too close to the boss or adds." },
		["Rift Slash"] = { localizedName = "Rift Slash", tooltipKind = "Boss Mechanic", tooltipText = "Stage 2 tank hit. Swap regularly to keep stacks and tank damage manageable." },
		["Silverstrike"] = { localizedName = "Silverstrike", tooltipKind = "Boss Mechanic", tooltipText = "Core silver-arrow mechanic. Cleanses void effects and supports target and add control." },
		["Cosmic Barrier"] = { localizedName = "Cosmic Barrier", tooltipKind = "Boss Mechanic", tooltipText = "Shield in Stage 2. Break it immediately before raid damage escalates." },
		["Coalesced Form"] = { localizedName = "Coalesced Form", tooltipKind = "Boss Mechanic", tooltipText = "Dangerous Voidspawn state. The adds need to be controlled and killed before this becomes relevant." },
		["Null Corona"] = { localizedName = "Null Corona", tooltipKind = "Boss Mechanic", tooltipText = "Dispellable debuff. Remove it in a controlled way instead of dispelling at random." },
		["Voidstalker Sting"] = { localizedName = "Voidstalker Sting", tooltipKind = "Boss Mechanic", tooltipText = "Major healing check. Depending on the strategy, silver arrows can help clear it." },
		["Devouring Cosmos"] = { localizedName = "Devouring Cosmos", tooltipKind = "Boss Mechanic", tooltipText = "Stage 3 movement mechanic. Use the feather and move to the next platform in time." },
		["Void Expulsion"] = { localizedName = "Void Expulsion", tooltipKind = "Boss Mechanic", tooltipText = "Targeted mechanic placed outward. On higher difficulties it can hit additional players." },
		["Barrage"] = { localizedName = "Barrage", tooltipKind = "Boss Mechanic", tooltipText = "Intermission mechanic with fixed calls. Lines and arrow paths need to stay clean." },
		["Silver Residue"] = { localizedName = "Silver Residue", tooltipKind = "Boss Mechanic", tooltipText = "Effect on sentinel targets that the raid actively uses with silver arrows to optimize the phase." },
		["Grasp of Emptiness"] = { localizedName = "Grasp of Emptiness", tooltipKind = "Boss Mechanic", tooltipText = "Targeted mechanic placed away from the raid. Poor placement punishes the group immediately." },
		["Rending Slash"] = "Rending Slash",
		["Implosion"] = { localizedName = "Implosion", aliases = { "implosion" } },
	},
	STREAMER_PLANNER_TITLE = "Group Planner",
	STREAMER_PLANNER_DESC = "A small transparent overlay for stream situations where you can sort signups directly into fixed dungeon or raid slots.",
	STREAMER_PLANNER_USAGE_HINT = "Click a slot in the preview or overlay, enter the name and confirm with Enter. Right-click a slot to clear it immediately.",
	STREAMER_PLANNER_PREVIEW_HINT = "The preview mirrors the same data as the overlay. You can use either view directly for editing.",
	STREAMER_PLANNER_SETTINGS_HINT = "Control mode, visibility and position of the planning overlay for your stream here.",
	STREAMER_PLANNER_SHOW_OVERLAY = "Show planning overlay",
	STREAMER_PLANNER_SHOW_OVERLAY_HINT = "Shows or hides the transparent overlay without losing the names you already entered.",
	STREAMER_PLANNER_LOCK_OVERLAY = "Lock planning overlay",
	STREAMER_PLANNER_LOCK_OVERLAY_HINT = "Locks the overlay at its current position so it does not get moved accidentally during the stream.",
	STREAMER_PLANNER_MODE = "Planning mode",
	STREAMER_PLANNER_MODE_HINT = "Switches between a 5-player dungeon setup and four raid groups with five slots each.",
	STREAMER_PLANNER_MODE_DUNGEON = "Dungeon",
	STREAMER_PLANNER_MODE_RAID = "Raid",
	STREAMER_PLANNER_DESTINATION = "Destination",
	STREAMER_PLANNER_DESTINATION_HINT = "Type where the run is going here, for example the raid name, dungeon or meeting point.",
	STREAMER_PLANNER_DESTINATION_EMPTY = "No destination entered yet",
	STREAMER_PLANNER_DESTINATION_MANUAL = "Enter manually",
	STREAMER_PLANNER_DESTINATION_CATEGORY = "Pool",
	STREAMER_PLANNER_DESTINATION_SUGGESTION = "Suggestion",
	STREAMER_PLANNER_DESTINATION_CATEGORY_S1 = "S1",
	STREAMER_PLANNER_DESTINATION_CATEGORY_DELVES = "Delves",
	STREAMER_PLANNER_DESTINATION_CATEGORY_MIDNIGHT = "Midnight",
	STREAMER_PLANNER_DESTINATION_CATEGORY_RAIDS = "Raids",
	STREAMER_PLANNER_DESTINATION_EDIT = "Edit destination",
	STREAMER_PLANNER_DESTINATION_EDIT_HINT = "Enter where this group or raid is planned to go.",
	STREAMER_PLANNER_DESTINATION_KEYSTONE = "Keystone level",
	STREAMER_PLANNER_DESTINATION_S1_MAGISTERS_TERRACE = "Magisters' Terrace",
	STREAMER_PLANNER_DESTINATION_S1_MAISARA_CAVERNS = "Maisara Caverns",
	STREAMER_PLANNER_DESTINATION_S1_NEXUS_POINT_XENAS = "Nexus-Point Xenas",
	STREAMER_PLANNER_DESTINATION_S1_WINDRUNNER_SPIRE = "Windrunner Spire",
	STREAMER_PLANNER_DESTINATION_S1_ALGETHAR_ACADEMY = "Algeth'ar Academy",
	STREAMER_PLANNER_DESTINATION_S1_PIT_OF_SARON = "Pit of Saron",
	STREAMER_PLANNER_DESTINATION_S1_SEAT_OF_THE_TRIUMVIRATE = "The Seat of the Triumvirate",
	STREAMER_PLANNER_DESTINATION_S1_SKYREACH = "Skyreach",
	STREAMER_PLANNER_DESTINATION_DELVE_ATAL_AMAN = "Atal'Aman",
	STREAMER_PLANNER_DESTINATION_DELVE_COLLEGIATE_CALAMITY = "Collegiate Calamity",
	STREAMER_PLANNER_DESTINATION_DELVE_DEN_OF_ECHOES = "Den of Echoes",
	STREAMER_PLANNER_DESTINATION_DELVE_PARHELION_PLAZA = "Parhelion Plaza",
	STREAMER_PLANNER_DESTINATION_DELVE_SHADOWGUARD_POINT = "Shadowguard Point",
	STREAMER_PLANNER_DESTINATION_DELVE_SUNKILLER_SANCTUM = "Sunkiller Sanctum",
	STREAMER_PLANNER_DESTINATION_DELVE_THE_DARKWAY = "The Darkway",
	STREAMER_PLANNER_DESTINATION_DELVE_THE_GRUDGE_PIT = "The Grudge Pit",
	STREAMER_PLANNER_DESTINATION_DELVE_THE_GULF_OF_MEMORY = "The Gulf of Memory",
	STREAMER_PLANNER_DESTINATION_DELVE_THE_SHADOW_ENCLAVE = "The Shadow Enclave",
	STREAMER_PLANNER_DESTINATION_DELVE_TORMENTS_RISE = "Torment's Rise",
	STREAMER_PLANNER_DESTINATION_DELVE_TWILIGHT_CRYPTS = "Twilight Crypts",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_WINDRUNNER_SPIRE = "Windrunner Spire",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_MAGISTERS_TERRACE = "Magisters' Terrace",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_MURDER_ROW = "Murder Row",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_DEN_OF_NALORAKK = "Den of Nalorakk",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_MAISARA_CAVERNS = "Maisara Caverns",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_THE_BLINDING_VALE = "The Blinding Vale",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_VOIDSCAR_ARENA = "Voidscar Arena",
	STREAMER_PLANNER_DESTINATION_MIDNIGHT_NEXUS_POINT_XENAS = "Nexus-Point Xenas",
	STREAMER_PLANNER_DESTINATION_RAID_VOIDSPIRE = "The Voidspire",
	STREAMER_PLANNER_DESTINATION_RAID_DREAMRIFT = "The Dreamrift",
	STREAMER_PLANNER_DESTINATION_RAID_MARCH_ON_QUEL_DANAS = "March on Quel'Danas",
	STREAMER_PLANNER_CLASS = "Class",
	STREAMER_PLANNER_CLASS_NONE = "No class",
	STREAMER_PLANNER_SPEC = "Specialization",
	STREAMER_PLANNER_SPEC_NONE = "No spec",
	STREAMER_PLANNER_SCALE = "Overlay scale",
	STREAMER_PLANNER_SCALE_HINT = "Adjusts the size of the transparent overlay without changing entries or position.",
	STREAMER_PLANNER_TIMER_DURATION = "Timer duration",
	STREAMER_PLANNER_TIMER_DURATION_VALUE = "%d min",
	STREAMER_PLANNER_TIMER_DURATION_HINT = "Controls which duration the stream timer starts with and which value reset restores.",
	STREAMER_PLANNER_RESET_POSITION_HINT = "Moves the overlay back to its default position near the center of the screen.",
	STREAMER_PLANNER_CLEAR_LAYOUT = "Clear current layout",
	STREAMER_PLANNER_CLEAR_LAYOUT_HINT = "Removes all names only from the currently selected dungeon or raid mode.",
	STREAMER_PLANNER_CLEAR_ALL = "Clear everything",
	STREAMER_PLANNER_CLEAR_ALL_HINT = "Wipes both dungeon and raid planning when you want a clean slate.",
	STREAMER_PLANNER_OVERLAY_CLEAR_ALL = "Clear all",
	STREAMER_PLANNER_EDIT_HINT = "Tip: Left-click edits a slot, right-click clears it instantly. That keeps stream signup handling quick.",
	STREAMER_PLANNER_OVERLAY_TITLE = "Group Planner",
	STREAMER_PLANNER_OVERLAY_CLOSE_TOOLTIP = "Hide overlay",
	STREAMER_PLANNER_OVERLAY_CLOSE_TOOLTIP_HINT = "Hides the planner overlay. You can enable it again from the module page at any time.",
	STREAMER_PLANNER_OVERLAY_SETTINGS_BUTTON = "Menu",
	STREAMER_PLANNER_OVERLAY_SETTINGS_TOOLTIP = "Open module settings",
	STREAMER_PLANNER_OVERLAY_SETTINGS_TOOLTIP_HINT = "Jumps directly to the group planner page in the addon window.",
	STREAMER_PLANNER_TIMER = "Timer",
	STREAMER_PLANNER_TIMER_START = "Start",
	STREAMER_PLANNER_TIMER_PAUSE = "Pause",
	STREAMER_PLANNER_TIMER_RESET = "Reset",
	STREAMER_PLANNER_TIMER_RUNNING = "Running",
	STREAMER_PLANNER_TIMER_PAUSED = "Paused",
	STREAMER_PLANNER_TIMER_EXPIRED = "Time elapsed: find randoms",
	STREAMER_PLANNER_EMPTY_SLOT = "empty",
	STREAMER_PLANNER_SLOT_EDIT = "Edit slot",
	STREAMER_PLANNER_SLOT_EDIT_HINT = "Enter the name or a short note for this slot here.",
	STREAMER_PLANNER_SAVE_SLOT = "Save",
	STREAMER_PLANNER_CLEAR_SLOT = "Clear",
	STREAMER_PLANNER_ROLE_TANK = "Tank",
	STREAMER_PLANNER_ROLE_HEALER = "Healer",
	STREAMER_PLANNER_ROLE_DPS1 = "DPS 1",
	STREAMER_PLANNER_ROLE_DPS2 = "DPS 2",
	STREAMER_PLANNER_ROLE_DPS3 = "DPS 3",
	STREAMER_PLANNER_RAID_SUMMARY = "Tanks: %d   Healers: %d   DPS: %d",
	STREAMER_PLANNER_RAID_GROUP = "Group %d",
	STREAMER_PLANNER_RAID_SLOT = "G%d / %d",
	STREAMER_PLANNER_QUEUE_TITLE = "Whisper Queue",
	STREAMER_PLANNER_QUEUE_HINT = "Only whispers with !enter or !inv are listed here. Role and spec are added when matching data is available. Right-click removes whisper entries. AutoInv works in dungeon and raid, but only if that player is already known via !enter. FullInv stays raid-only.",
	STREAMER_PLANNER_AUTO_INVITE_WHISPER = "Auto invite on !inv",
	STREAMER_PLANNER_FULL_INVITE = "FullInv",
	STREAMER_PLANNER_QUEUE_EMPTY = "No whisper entries yet.",
	STREAMER_PLANNER_SPEC_PROMPT_TITLE = "Choose spec",
	STREAMER_PLANNER_SPEC_PROMPT_HINT = "Someone wants to join the planner via !enter. Pick the specialization so the correct slot can be assigned.",
	STREAMER_PLANNER_SPEC_PROMPT_CLASS = "Class: %s",
	STREAMER_PLANNER_SPEC_PROMPT_LATER = "Later",
	STREAMER_PLANNER_SPEC_PROMPT_REMOVE = "Remove",
	STREAMER_PLANNER_SOURCE_LFG = "LFG",
	STREAMER_PLANNER_SOURCE_WHISPER_ENTER = "Whisper !enter",
	STREAMER_PLANNER_SOURCE_WHISPER_INV = "Whisper !inv",
	STREAMER_PLANNER_STATUS_GROUPED = "In group",
	STREAMER_PLANNER_STATUS_INVITED = "Invited",
	STREAMER_PLANNER_STATUS_WHISPER_ENTER = "Waiting for invite",
	STREAMER_PLANNER_STATUS_WHISPER_INV = "Wants invite",
	MARKER_BAR_DESC = "A compact overlay bar for target markers and world markers. A normal click marks your current target, while Shift-click prepares the matching ground marker.",
	MARKER_BAR_USAGE_HINT = "Normal click sets the target marker. Shift-click activates the matching world marker. The bar stays intentionally small, transparent and easy to keep in view.",
	MARKER_BAR_PERMISSION_HINT = "Note: Markers only work if your group or raid permissions allow you to place them.",
	MARKER_BAR_SHOW_OVERLAY = "Show marker bar",
	MARKER_BAR_LOCK_OVERLAY = "Lock marker bar",
	MARKER_BAR_SCALE = "Scale",
	MARKER_BAR_SCALE_HINT = "Adjusts the size of the transparent bar without changing which marker each button triggers.",
	MARKER_BAR_RESET_POSITION = "Reset bar position",
	MARKER_BAR_OVERLAY_HINT = "Click = mark target | Shift = world marker",
	MARKER_BAR_DRAG_HINT = "Unlock the bar and drag it by the edge to move it.",
	CAMERA_DISTANCE_HINT = "Sets the maximum camera distance to the standard value or the maximum value and reapplies the setting after login.",
	CURRENT_SETTING = "Current setting:",
	CAMERA_DISTANCE_MAX = "Max Distance",
	CAMERA_DISTANCE_QUESTION = "?",
	CAMERA_DISTANCE_MODE_MAX = "max",
	CAMERA_DISTANCE_MODE_STANDARD = "standard",
	CAMERA_DISTANCE_MODE_CUSTOM = "custom",
	CAMERA_DISTANCE_MODE_UNKNOWN = "unknown",
	CAMERA_DISTANCE_STATUS_MAX = "Max Distance (%s)",
	CAMERA_DISTANCE_STATUS_STANDARD = "Standard (%s)",
	CAMERA_DISTANCE_STATUS_CUSTOM = "Custom (%s)",
	CAMERA_DISTANCE_STATUS_UNKNOWN = "Unknown",
	AUTOREPAIR_GUILD_DONE = "Beavis QoL: Repaired using guild funds.",
	AUTOREPAIR_DONE = "Beavis QoL: Repaired for %s.",
	AUTOSELL_UNKNOWN_ITEM = "Unknown item",
	AUTOSELL_SUMMARY = "Beavis QoL: sold %d junk item(s) for %s.",
	STANDARD = "Standard",

	VERSIONS_INFO_TITLE = "%s - Version Info",
	VERSIONS_INFO_DESC = "Here you can find the most important information about the installed version and an in-game notice if you encounter someone with a higher BeavisQoL version.",
	CURRENT_VERSION = "Current Version",
	RELEASE_DATE = "Release Date",
	PROGRAMMER = "Developer",
	SUPPORTED_GAME_VERSION = "Supported Game Version",
	TOC_VERSION = "TOC Version",
	VERSION_CHECK = "Version Check",
	VERSION_CHECK_AVAILABLE = "New version available: %s",
	VERSION_CHECK_SEEN_AT = "Seen on %s via %s. Currently installed is %s.",
	VERSION_CHECK_CHANNEL = "a group channel",
	VERSION_CHECK_HINT = "Note: The comparison works via party, raid, instance chat or guild and not directly via GitHub.",
	VERSION_CHECK_CURRENT = "Up to date",
	VERSION_CHECK_CURRENT_TEXT = "As soon as an update is available, you will get information here.",
	VERSION_CHECK_CURRENT_SUBTEXT = "Installed: %s | Release date: %s",
	VERSION_COMPARE_NOW = "Check now",
	VERSION_RELEASE_LINK = "Release link",
	CONTACT_TITLE = "Contribute & Contact",
	CONTACT_TEXT = "If you want to give feedback or submit new ideas, you can contact us directly via the Beavismania website.",
	SEND_FEEDBACK = "Send feedback",
	SUBMIT_IDEA = "Submit idea",
	RELEASES_POPUP = "BeavisQoL Releases",
	FEEDBACK_POPUP = "Send feedback",
	IDEA_POPUP = "Submit idea",

	DAMAGE_TEXT_DESC = "Here you can visually customize Blizzard damage numbers. Font and movement behavior are changed directly through the existing combat text systems.",
	DAMAGE_TEXT_CONFLICT = "Conflict: NiceDamage is loaded and may override your combat text. Please disable NiceDamage for this character if you want to use Beavis QoL.",
	DAMAGE_TEXT_ENABLE_TITLE = "Use custom combat text adjustments",
	DAMAGE_TEXT_ENABLE_HINT = "Replaces the Blizzard combat text font and adjusts the movement of damage numbers via scale, gravity and ramp duration.",
	DAMAGE_TEXT_APPEARANCE_HINT = "Custom fonts can be added manually through the addon's Fonts folder and will then appear directly in the selection.",
	DAMAGE_TEXT_RESTART_HINT = "After changing the font, the game must be fully closed and restarted so the change is applied safely.",

	LFG_DESC = "Here you will find comfort features for the premade group finder.",
	FLAGS_TITLE = "Country Flags",
	FLAGS_HINT = "Shows a small flag next to applicants in the premade group finder based on their realm.",
	LFG_LISTING_PRESET_TITLE = "Listing presets",
	LFG_LISTING_PRESET_HINT = "Stores presets for your own group listing. The dropdown is applied automatically; for name and details, BeavisQoL shows copy buttons next to Blizzard's protected text fields.",
	LFG_LISTING_PRESET_ENABLE = "Enable listing preset helper",
	LFG_LISTING_PRESET_ENABLE_HINT = "When enabled, BeavisQoL applies the saved dropdown preset and shows copy buttons for protected text fields in Blizzard's creation window.",
	LFG_LISTING_NAME_SUFFIX = "Name presets",
	LFG_LISTING_NAME_SUFFIX_HINT = "Stores texts appended to the game-prefilled name. In the creation window, the paper button opens the presets as a menu.",
	LFG_LISTING_DETAILS = "Details presets",
	LFG_LISTING_DETAILS_HINT = "Stores details blocks as templates. In the creation window, the paper button opens the presets as a menu.",
	LFG_LISTING_PRESET_SLOT = "Preset %d",
	LFG_LISTING_PRESET_MENU_LABEL = "Preset %d: %s",
	LFG_LISTING_COPY_NAME_LABEL = "Name preset",
	LFG_LISTING_COPY_DETAILS_LABEL = "Details preset",
	LFG_LISTING_COPY_NAME_TOOLTIP = "Copy name preset",
	LFG_LISTING_COPY_NAME_TOOLTIP_DESC = "Opens the current group name including your saved suffix in a highlighted copy field. Press Ctrl+C, then paste it into Blizzard's field.",
	LFG_LISTING_COPY_DETAILS_TOOLTIP = "Copy details preset",
	LFG_LISTING_COPY_DETAILS_TOOLTIP_DESC = "Opens your saved details block in a highlighted copy field. Press Ctrl+C, then paste it into Blizzard's field.",
	LFG_LISTING_COPY_DIALOG_TITLE = "Copy %s",
	LFG_LISTING_COPY_DIALOG_HINT = "The text is highlighted. Press Ctrl+C to copy it, then paste it into Blizzard's field.",
	LFG_LISTING_COPY_EMPTY = "No preset text saved to copy.",
	LFG_LISTING_SETTINGS_BUTTON_TOOLTIP = "BeavisQoL presets",
	LFG_LISTING_SETTINGS_BUTTON_TOOLTIP_DESC = "Opens the Group Finder settings for name, details and dropdown presets directly.",
	LFG_LISTING_PLAYSTYLE = "Dropdown default",
	LFG_LISTING_PLAYSTYLE_HINT = "Automatically selects the saved dropdown option while creating a listing. \"No default\" keeps Blizzard's normal behavior unchanged.",
	LFG_LISTING_PLAYSTYLE_NONE = "No default",
	LFG_LISTING_PLAYSTYLE_LEARNING = "Learning",
	LFG_LISTING_PLAYSTYLE_RELAXED = "Relaxed",
	LFG_LISTING_PLAYSTYLE_COMPETITIVE = "Competitive",
	LFG_LISTING_PLAYSTYLE_EXPERT = "Boost offered",
	EASY_LFG_TITLE = "Easy LFG",
	EASY_LFG_HINT = "Shows a small transparent applicant overlay for your own listing so you can see and invite applicants without keeping the large Blizzard window open.",
	EASY_LFG_SHOW_OVERLAY = "Enable Easy LFG overlay",
	EASY_LFG_SHOW_OVERLAY_HINT = "Automatically shows the compact applicant window whenever your own group listing is active.",
	EASY_LFG_LOCK_OVERLAY = "Lock Easy LFG overlay",
	EASY_LFG_LOCK_OVERLAY_HINT = "Locks the small applicant window in place so it does not get moved accidentally.",
	EASY_LFG_SCALE = "Overlay scale",
	EASY_LFG_SCALE_HINT = "Adjusts the size of the Easy LFG window without changing entries or position.",
	EASY_LFG_BACKGROUND_ALPHA = "Background transparency",
	EASY_LFG_TEXT_SCALE = "Text scale",
	EASY_LFG_TEXT_SCALE_HINT = "Adjusts only the font size inside the Easy LFG overlay, independent of the window size.",
	EASY_LFG_BACKGROUND_ALPHA_HINT = "Controls how visible the applicant window background stays.",
	EASY_LFG_RESET_HINT = "Moves the Easy LFG window back to its default position to the right of your character.",
	INVITE_TIMER_TITLE = "Invite Timer",
	INVITE_TIMER_HINT = "Adds a small countdown bar with seconds directly to queue ready windows such as dungeon finder, LFR, arena and battleground invites.",
	INVITE_TIMER_ENABLED = "Show invite timer bars",
	INVITE_TIMER_ENABLED_HINT = "Displays a compact countdown bar inside supported ready dialogs until the invite expires.",
	INVITE_TIMER_COUNTDOWN_SOUND = "Countdown sound from 5 seconds",
	INVITE_TIMER_COUNTDOWN_SOUND_HINT = "Plays a spoken five, four, three, two, one during the last five seconds.",
	EASY_LFG_OVERLAY_TITLE = "Easy LFG",
	EASY_LFG_OVERLAY_SUMMARY = "%d applicants | %d players",
	EASY_LFG_OVERLAY_EMPTY = "No applicants in queue yet.",
	EASY_LFG_OVERLAY_NO_GROUP = "Easy LFG appears automatically once your own group listing is active.",
	EASY_LFG_OVERLAY_NO_GROUP_SHORT = "No active group",
	EASY_LFG_OVERLAY_MORE = "+%d more players hidden",
	EASY_LFG_OVERLAY_RESIZE_HINT = "Drag the bottom right corner to resize the window.",
	EASY_LFG_OVERLAY_CLOSE_TOOLTIP = "Hide Easy LFG",
	EASY_LFG_OVERLAY_CLOSE_TOOLTIP_HINT = "Hides the overlay for the current active listing. It will appear automatically again on your next own listing.",
	EASY_LFG_OVERLAY_PIN = "Pin",
	EASY_LFG_OVERLAY_UNPIN = "Unpin",
	EASY_LFG_OVERLAY_PIN_TOOLTIP = "Lock overlay",
	EASY_LFG_OVERLAY_UNPIN_TOOLTIP = "Unlock overlay",
	EASY_LFG_OVERLAY_PIN_TOOLTIP_HINT = "Locks or unlocks the position of the Easy LFG overlay.",
	EASY_LFG_DECLINE = "Decline",
	EASY_LFG_INVITE = "Invite",
	EASY_LFG_ITEM_LEVEL = "ilvl %s",
	EASY_LFG_SCORE = "Score %d",
	EASY_LFG_GROUP_BADGE = "%d players",
	EASY_LFG_MEMBER_INDEX = "%d/%d",
	EASY_LFG_STATUS_APPLIED = "Applied",
	EASY_LFG_STATUS_INVITED = "Invited",
	EASY_LFG_STATUS_INVITE_ACCEPTED = "Invite accepted",
	EASY_LFG_STATUS_DECLINED = "Declined",
	EASY_LFG_STATUS_INVITE_DECLINED = "Invite declined",
	EASY_LFG_STATUS_INACTIVE = "Inactive",

	PET_STUFF_DESC = "Here you will find small comfort features for companions and pets.",
	AUTO_RESPAWN_PET_TITLE = "Pet Options",
	AUTO_RESPAWN_PET_HINT = "Automatically resummons your last active companion pet after mounting and dismounting. Resummoning is only possible out of combat.",

	ITEM_GUIDE_EYEBROW = "Progress",
	ITEM_GUIDE_TITLE = "Midnight S1 Itemlevel Compass",
	ITEM_GUIDE_SUBTITLE = "Upgrade paths, crafting, dungeons, raid and delves compactly on one page.",
	ITEM_GUIDE_DESC = "The values are intended as a quick seasonal reference. The raid item levels in particular are deliberately marked as guidelines so the page works like a calm reference in everyday play and not like a cramped list of numbers.",
	SEASON_REFERENCE = "Season Reference",
	ITEM_GUIDE_BADGE_TEXT = "20 crests per rank\nRaid values = approx.",
	ITEM_GUIDE_LEGEND = "|cff45ff6eAdventurer|r  -  |cff2e94ffVeteran|r  -  |cffba57ffChampion|r  -  |cffff9220Hero|r  -  |cffffe033Myth|r",
	ITEM_GUIDE_UPGRADE_CARD_TITLE = "Crest Paths",
	ITEM_GUIDE_UPGRADE_CARD_SUBTITLE = "Upgrade paths and crests",
	ITEM_GUIDE_UPGRADE_CARD_NOTE = "20 crests per rank, saving points marked directly.",
	ITEM_GUIDE_PATH_ADVENTURER = "Adventurer",
	ITEM_GUIDE_PATH_VETERAN = "Veteran",
	ITEM_GUIDE_PATH_CHAMPION = "Champion",
	ITEM_GUIDE_PATH_HERO = "Hero",
	ITEM_GUIDE_PATH_MYTH = "Myth",
	ITEM_GUIDE_SAVE_VETERAN = "save for Veteran",
	ITEM_GUIDE_SAVE_CHAMPION = "save for Champion",
	ITEM_GUIDE_SAVE_HERO = "save for Hero",
	ITEM_GUIDE_SAVE_MYTH = "save for Myth",
	ITEM_GUIDE_SAVE_FOR_RUNED = "save for Runed",
	ITEM_GUIDE_SAVE_FOR_GILDED = "save for Gilded",
	ITEM_GUIDE_HEADER_PATH_RANK = "Path / Rank",
	ITEM_GUIDE_HEADER_CRESTS = "Crests",
	ITEM_GUIDE_HEADER_QUALITY = "Quality",
	ITEM_GUIDE_HEADER_SOURCE = "Source",
	ITEM_GUIDE_HEADER_END_REWARD = "End Reward",
	ITEM_GUIDE_HEADER_GREAT_VAULT = "Great Vault",
	ITEM_GUIDE_HEADER_DIFFICULTY = "Difficulty",
	ITEM_GUIDE_HEADER_EARLY = "Early",
	ITEM_GUIDE_HEADER_MID = "Mid",
	ITEM_GUIDE_HEADER_LATE = "Late",
	ITEM_GUIDE_HEADER_END = "End",
	ITEM_GUIDE_HEADER_LEVEL = "Level",
	ITEM_GUIDE_HEADER_MAP_DROP = "Map Drop",
	ITEM_GUIDE_LABEL_HEROIC = "Heroic",
	ITEM_GUIDE_LABEL_MYTHIC = "Mythic",
	ITEM_GUIDE_LABEL_RAID_FINDER = "Raid Finder",
	ITEM_GUIDE_LABEL_NORMAL = "Normal",
	ITEM_GUIDE_ABBR_ADVENTURER = "Adv.",
	ITEM_GUIDE_ABBR_VETERAN = "Vet.",
	ITEM_GUIDE_ABBR_CHAMPION = "Champ.",
	ITEM_GUIDE_ABBR_HERO = "Hero",
	ITEM_GUIDE_ABBR_MYTH = "Myth",
	ITEM_GUIDE_CRAFTED_CARD_TITLE = "Crafting",
	ITEM_GUIDE_CRAFTED_CARD_SUBTITLE = "Crafted item levels",
	ITEM_GUIDE_CRAFTED_CARD_NOTE = "Quality and target path in one compact matrix.",
	ITEM_GUIDE_DUNGEON_CARD_TITLE = "Instances",
	ITEM_GUIDE_DUNGEON_CARD_SUBTITLE = "Dungeon and Great Vault",
	ITEM_GUIDE_DUNGEON_CARD_NOTE = "Heroic, Mythic and M+ at a glance.",
	ITEM_GUIDE_RAID_CARD_TITLE = "Raid",
	ITEM_GUIDE_RAID_CARD_SUBTITLE = "Raid guidelines",
	ITEM_GUIDE_RAID_CARD_NOTE = "Early to late bosses as a rough seasonal reference.",
	ITEM_GUIDE_DELVE_CARD_TITLE = "Delves",
	ITEM_GUIDE_DELVE_CARD_SUBTITLE = "Delves and weekly chest",
	ITEM_GUIDE_DELVE_CARD_NOTE = "End reward, map drop and Great Vault.",
	ITEM_GUIDE_UPGRADE_FOOTNOTE = "The red hints mark spots where saving the next crest color is usually more worthwhile.",
	ITEM_GUIDE_RAID_FOOTNOTE = "Raid values are deliberately phrased as approximate and can vary slightly by boss.",
	ITEM_GUIDE_FOOTER = "Goal of this page: quick decisions in everyday play. One glance is enough to compare upgrade path, dungeon target or crafting tier.",

	LEVELTIME_TOOLTIP_TITLE = "Level Time Tracker",
	LEVELTIME_TOOLTIP_TEXT = "The level time tracker only counts time actually played while the addon is active.",
	LEVEL_LABEL = "Level %d",
	CURRENT_LEVEL = "Current Level",
	TIME_ON_CURRENT_LEVEL = "Time on current level",
	TOTAL_TIME = "Total time",
	TRACKED_LEVEL_TIMES = "Tracked level times",
	LEVEL_RUNNING = "currently running",
	MAX_LEVEL_REACHED = "Maximum level reached",
	MAX_LEVEL_CONGRATS = "Congratulations, you reached the maximum level.",

	QUESTCHECK_TITLE = "Quest Check",
	QUESTCHECK_DESC = "Checks whether a quest has already been completed. You can enter a quest ID, a WoWHead link, or an exact quest name directly.",
	QUEST_SEARCH = "Search Quest",
	QUEST_SEARCH_HINT = "Examples: Quest ID 12345, an exact quest name or https://www.wowhead.com/quest=12345",
	CHECK_QUEST = "Check quest",
	RESULT = "Result",
	QUESTCHECK_RESULT_HINT = "The quest completion status will appear here after the search.",
	QUESTCHECK_NO_SEARCH = "No search executed yet.",
	QUESTCHECK_READY_TO_SEARCH = "Ready to search",
	WOWHEAD_LINK = "WoWHead link",
	WOWHEAD_SEARCH = "WoWHead search",
	LINKS_COPY_DIALOG = "Links are shown in the copy dialog.",
	QUESTCHECK_INPUT_MISSING = "Please enter a quest ID, an exact quest name or a WoWHead link.",
	QUESTCHECK_SEARCH_RUNNING = "Searching",
	QUESTCHECK_SCANNING = "The quest name is being checked against locally known quest titles. This may take a moment on the first run.",
	QUESTCHECK_SCAN_PROGRESS = "Searching local quest names: %.0f%%",
	QUEST_DONE = "|cff55dd55Completed|r",
	QUEST_NOT_DONE = "|cffff6666Not completed|r",
	QUEST_IN_LOG = "in quest log",
	QUEST_WARBAND_DONE = "warband completed",
	QUEST_ID_LABEL = "Quest ID %d",
	QUEST_RESULT_LINE = "[%d] %s - %s%s",
	QUEST_MORE_RESULTS = "|cffbfbfbf+ %d more matches|r",
	QUEST_SINGLE_SOURCE_ID = "Direct ID check",
	QUEST_SINGLE_SOURCE_NAME = "Name search",
	QUEST_SINGLE_TEXT = "Quest \"%s\" (ID %d) | %s",
	QUEST_SINGLE_CHAT = "Quest \"%s\" (ID %d) is %s.",
	QUEST_SINGLE_CHAT_ACTIVE = " It is currently in the quest log.",
	QUEST_SINGLE_CHAT_WARBAND = " It is already completed warband-wide.",
	QUEST_WOWHEAD_TITLE = "Quest on WoWHead",
	QUEST_MULTIPLE_STATE = "%d matches",
	QUEST_MULTIPLE_TEXT = "Multiple quests with exactly this name were found locally. Please choose the correct quest ID from the list.",
	QUEST_MULTIPLE_CHAT = "%d quests with the name \"%s\" found. Details are shown in the Quest Check module.",
	QUEST_UNRESOLVED_TEXT = "The quest name could not be resolved locally to a unique quest ID. Checking by quest ID is the most reliable method.",
	QUEST_UNRESOLVED_TIPS = "Tips:\n- use the exact quest name\n- alternatively enter a quest ID or a WoWHead link directly",
	QUEST_UNRESOLVED_CHAT = "Quest name \"%s\" could not be resolved locally. Checking by quest ID is the safest method.",
	QUEST_INPUT_MISSING_STATE = "Missing input",
	QUEST_NOT_DONE_PLAIN = "not completed",
	QUEST_DONE_PLAIN = "completed",
	QUEST_ABANDON_TITLE = "Quest Abandon",
	QUEST_ABANDON_LIST_TITLE = "Quest List",
	QUEST_ABANDON_DESC = "Choose exactly which visible active quests should be abandoned. The action affects your current quest log immediately and asks for confirmation before abandoning.",
	QUEST_ABANDON_SELECT_ALL = "Select all",
	QUEST_ABANDON_CLEAR_ALL = "Clear all",
	QUEST_ABANDON_SELECTED = "Abandon selected",
	QUEST_ABANDON_UNAVAILABLE = "Quest abandonment is not available here through the current API.",
	QUEST_ABANDON_NONE = "There are currently no active quests in the quest log.",
	QUEST_ABANDON_SELECTION_COUNT = "%d of %d quests selected",
	QUEST_ABANDON_SELECTED_NONE = "No quests are selected for abandonment.",
	QUEST_ABANDON_CONFIRM = "Really abandon %d selected quest(s)?",
	QUEST_ABANDON_DONE = "%d quest(s) were abandoned.",
	LIVE_PREVIEW = "Live Preview",
	DISPLAY_POSITION = "Display and Position",
	WINDOW_SCALE = "Window Scale",
	BACKGROUND_ALPHA = "Background Opacity",
	FONT_SIZE_OVERLAY = "Overlay Font Size",
	RESET_POSITION_HINT = "Resets the overlay to its default position at the bottom right.",
	SHOW_OVERLAY = "Show overlay",
	LOCK_OVERLAY = "Lock overlay",

	STATS_TITLE = "Stats",
	STATS_DESC = "Shows your most important secondary stats in a small, subtle in-game window. The preview below already uses your current gear, buffs and procs.",
	STATS_PREVIEW_HINT = "This is how the small stats window looks in-game: compact, clean and intentionally unobtrusive.",
	STATS_PREVIEW_FOOTER = "Font size, scale and transparency apply directly to the live preview.",
	STATS_SETTINGS_HINT = "The stats window is freely movable, transparent and intentionally compact. Font size and scale can be adjusted separately.",
	STATS_SHOW_OVERLAY = "Show stats window",
	STATS_SHOW_OVERLAY_HINT = "Shows a small window with your current values outside the main window.",
	STATS_LOCK_OVERLAY = "Lock stats window",
	STATS_LOCK_OVERLAY_HINT = "Locks free movement once the position suits you.",
	STATS_FONT_SIZE = "Stats window font size",
	STATS_RESET_HINT = "Resets the small stats window to the default position at the bottom right.",

	WEEKLY_KEYS_DESC = "Shows you the 8 highest weekly keys in a transparent, frameless overlay. Rows 1, 4 and 8 directly show the respective weekly loot item level.",
	WEEKLY_KEYS_PREVIEW_HINT = "The preview shows the same clean style as the in-game overlay, but intentionally without a visible frame.",
	WEEKLY_KEYS_PREVIEW_FOOTER = "Font size, scale and transparency apply directly to the live preview.",
	WEEKLY_KEYS_SETTINGS_HINT = "The overlay is intentionally frameless and subtle. Font size and scale can be adjusted separately to make it more compact.",
	WEEKLY_KEYS_SHOW_OVERLAY = "Show weekly keys overlay",
	WEEKLY_KEYS_SHOW_OVERLAY_HINT = "Shows the top 8 keys with weekly loot hints outside the main window.",
	WEEKLY_KEYS_LOCK_OVERLAY = "Lock overlay",
	WEEKLY_KEYS_LOCK_OVERLAY_HINT = "Locks free movement once the position suits you.",
	WEEKLY_KEYS_HIDE_IN_RAID = "Hide in raids",
	WEEKLY_KEYS_HIDE_IN_RAID_HINT = "Automatically hides the weekly keys overlay while you are in a raid group.",
	WEEKLY_KEYS_RESET_HINT = "Resets the overlay to its default position at the bottom right.",
	WEEKLY_KEYS_HEROIC = "HC",
	WEEKLY_KEYS_MYTHIC = "Mythic",
	WEEKLY_KEYS_HEROIC_RECORDED = "Heroic dungeon recorded",
	WEEKLY_KEYS_MYTHIC_RECORDED = "Mythic dungeon recorded",
	WEEKLY_KEYS_NAMELESS = "Dungeon recorded without name",
	UNKNOWN_DUNGEON = "Unknown dungeon",
	WEEKLY_KEYS_PLACEHOLDER = "Dungeon without name recorded",
	WEEKLY_KEYS_NONE_THIS_WEEK = "No dungeon this week yet",
	WEEKLY_KEYS_NONE_WEEKLY = "No weekly dungeon completed yet",
	WEEKLY_KEYS_MORE_NEEDED = "%d more %s until weekly slot",
	DUNGEON_SINGULAR = "Dungeon",
	DUNGEON_PLURAL = "Dungeons",
	WEEKLY_KEYS_SUMMARY = "%d/8 Dungeons | Weekly loot %s / %s / %s",

	LOGGING_DESC = "Compact logs for income, expenses, repairs and currencies. Full history is available via History.",
	LOGGING_CLEANUP = "Delete time range",
	LOGGING_RETENTION_HINT = "Repairs 30 days, gold and currencies 1 year.",
	LOGGING_CLEANUP_TITLE = "Delete log time range",
	LOGGING_CLEANUP_HINT = "Removes entries older than the selected period. Repairs additionally remain automatically limited to 30 days.",
	LOGGING_SALES_TITLE = "Sales log",
	LOGGING_SALES_HINT = "Shows the latest vendor sales, including Auto Sell Junk. Entries with item data can be expanded with a click.",
	LOGGING_REPAIRS_TITLE = "Repair costs",
	LOGGING_REPAIRS_HINT = "Last 10 days. Full history is available via History.",
	LOGGING_INCOME_TITLE = "Income with source",
	LOGGING_INCOME_HINT = "Last 10 income entries. Full history is available via History.",
	LOGGING_EXPENSE_TITLE = "Expenses with target",
	LOGGING_EXPENSE_HINT = "Last 10 expense entries. Full history is available via History.",
	LOGGING_CURRENCY_TITLE = "Other currencies",
	LOGGING_CURRENCY_HINT = "Last 10 changes. Full history is available via History.",
	LOGGING_HISTORY = "History",
	LOGGING_HISTORY_TITLE = "Full History",
	LOGGING_HISTORY_HINT = "Search the history or switch between categories.",
	LOGGING_HISTORY_EMPTY = "No history available yet.",
	LOGGING_HISTORY_TAB_INCOME = "Income",
	LOGGING_HISTORY_TAB_EXPENSE = "Expenses",
	LOGGING_HISTORY_TAB_REPAIRS = "Repairs",
	LOGGING_HISTORY_TAB_CURRENCY = "Currencies",
	LOGGING_HISTORY_SEARCH = "Search",
	LOGGING_HISTORY_LOAD_MORE = "Load more",
	LOGGING_HISTORY_NO_MATCHES = "No matches in the active history.",
	LOGGING_OVERVIEW_NO_MATCHES = "No matches for this search.",
	LOGGING_HISTORY_SHOWING = "%d entries visible.",
	LOGGING_HISTORY_SHOWING_MORE = "%d entries visible. More entries can be loaded.",
	LOGGING_STORED_SALES = "Saved sales: %d",
	LOGGING_TOTAL_SALES_GOLD = "Total gold from sales: %s",
	LOGGING_STORED_REPAIRS = "Saved repairs: %d",
	LOGGING_TOTAL_REPAIRS = "Total repair costs: %s",
	LOGGING_DAILY_EXPAND_HINT = "Daily totals can be expanded.",
	LOGGING_NO_REPAIRS = "No repairs have been logged yet.",
	LOGGING_STORED_INCOME = "Saved income: %d",
	LOGGING_TOTAL_INCOME = "Total amount: %s",
	LOGGING_STORED_EXPENSES = "Saved expenses: %d",
	LOGGING_TOTAL_EXPENSES = "Total amount: %s",
	LOGGING_STORED_CURRENCY_CHANGES = "Saved currency changes: %d",
	LOGGING_LATEST_ENTRIES = "Latest entries:",
	DAYS_7 = "7 days",
	DAYS_30 = "30 days",
	DAYS_90 = "90 days",
	DAYS_365 = "1 year",
	ALL = "All",
	DAILY = "Daily",
	WEEKLY = "Weekly",
	VAULT = "Vault",
	NO_ENTRIES = "No entries yet.",
	UNKNOWN_ITEM = "Unknown item",
	LOGGING_SALE = "Sale",
	LOGGING_VENDOR_SALE = "Vendor",
	LOGGING_MAIL = "Mail",
	LOGGING_MAILBOX = "Mailbox",
	LOGGING_AUCTIONHOUSE = "Auction House",
	LOGGING_TRADE = "Trade",
	LOGGING_QUEST = "Quest",
	LOGGING_QUEST_REWARD = "Quest reward",
	LOGGING_LOOT = "Loot",
	LOGGING_PICKED_UP = "Picked up",
	LOGGING_MISC = "Miscellaneous",
	LOGGING_FLIGHTMASTER = "Flight Master",
	LOGGING_VENDOR = "Vendor",
	LOGGING_TRAINER = "Trainer",
	LOGGING_REPAIR = "Repair",
	LOGGING_OWN_GOLD = "Own Gold",
	LOGGING_GUILD = "Guild",
	LOGGING_AUTOSELL = "Auto Sell Junk",
	LOGGING_COSTS = "Costs",
	LOGGING_SALE_TO = "Sale to %s",
	LOGGING_ITEM = "Item",
	LOGGING_ITEMS = "Items",
	LOGGING_REPAIRS = "Repairs",
	LOGGING_SELF_PAID = "Self paid",
	LOGGING_ENTRY = "Entry",
	ITEMS_LABEL = "Items",
	PET_STUFF_TITLE = "Pet Stuff",
	SEASON_NAME_MIDNIGHT = "Midnight",
	CHECKLIST_DESC = "Keeps daily, weekly and custom tasks compactly in view, optionally in a separate tracker window.",
	CHECKLIST_SUMMARY = "%d / %d completed",
	CHECKLIST_INTRO_SUMMARY_DEFAULT = "0 / 0 completed",
	CHECKLIST_INTRO_HINT = "Built-in tasks are already sorted. You can add your own tasks below as daily or weekly entries.",
	CHECKLIST_WATCH = "Watch",
	CHECKLIST_WATCH_SHORT = "Watch",
	CHECKLIST_WATCH_HINT = "Long-term points without an automatic reset that you simply want to keep an eye on.",
	CHECKLIST_EMPTY_WATCH = "There are currently no tasks in this category.",
	CHECKLIST_DAILY_HINT = "All tasks that reset with the daily EU reset. Built-in tasks can be disabled on the right.",
	CHECKLIST_EMPTY_DAILY = "There are currently no daily tasks.",
	CHECKLIST_WEEKLY_HINT = "All tasks that reset with the weekly EU reset.",
	CHECKLIST_EMPTY_WEEKLY = "There are currently no weekly tasks.",
	CHECKLIST_MANUAL_ADD_TITLE = "Add manual task",
	CHECKLIST_MANUAL_ADD_HINT = "Manual tasks can be added here by category. The selected category determines the automatic reset behavior.",
	CHECKLIST_MANUAL_ADD_LABEL = "New manual task",
	CHECKLIST_MANUAL_CATEGORY_HINT = "Tip: You can change the category later.",
	CHECKLIST_APPEARANCE = "Display and Appearance",
	CHECKLIST_APPEARANCE_HINT = "For tracking, you have a window in the interface that can be configured manually here.",
	CHECKLIST_SHOW_TRACKER = "Show tracker window",
	CHECKLIST_SHOW_TRACKER_HINT = "Shows a small checklist window outside the main window.",
	CHECKLIST_SHOW_BUILTIN = "Show built-in tasks in tracker",
	CHECKLIST_SHOW_BUILTIN_HINT = "Shows the fixed starter list in the small tracker window as well.",
	CHECKLIST_SHOW_MANUAL = "Show manual tasks in tracker",
	CHECKLIST_SHOW_MANUAL_HINT = "Shows your own tasks in the small tracker window as well.",
	CHECKLIST_HIDE_COMPLETED = "Hide completed to-dos in tracker",
	CHECKLIST_HIDE_COMPLETED_HINT = "Useful for a calmer in-game view when only open tasks should remain visible.",
	CHECKLIST_TRACKER_FONT_SIZE = "Tracker font size",
	CHECKLIST_RESET_CHECKS = "Reset all checkmarks",
	CHECKLIST_RESET_BUILTIN = "Reset built-in tasks",
	CHECKLIST_RESET_TRACKER = "Reset tracker window",
	CHECKLIST_TRACKER_EMPTY_OPEN = "No to-dos visible for the tracker.",
	CHECKLIST_TRACKER_EMPTY_HIDDEN = "No open to-dos visible for the tracker.",
	CHECKLIST_TRACKER_TITLE = "Checklist %d/%d",
	CHECKLIST_TRACKER_LOCKED = "Tracker locked",
	CHECKLIST_TRACKER_LOCKED_HINT = "Dragging and resizing are locked. Click to unlock.",
	CHECKLIST_TRACKER_UNLOCKED = "Tracker free",
	CHECKLIST_TRACKER_UNLOCKED_HINT = "Dragging and resizing are possible. Click to lock.",
	CHECKLIST_SETTINGS_BUTTON = "Cfg.",
	CHECKLIST_SETTINGS_TOOLTIP = "Checklist settings",
	CHECKLIST_SETTINGS_TOOLTIP_HINT = "Opens the checklist page directly at the settings section.",
	CHECKLIST_ADD_BUTTON = "Add",
	CHECKLIST_ADD_TOOLTIP = "Add task",
	CHECKLIST_ADD_TOOLTIP_HINT = "Opens a small window to quickly create a manual task.",
	CHECKLIST_VAULT_TOOLTIP = "Weekly Vault",
	CHECKLIST_VAULT_TOOLTIP_HINT = "Opens or closes the weekly rewards window.",
	CHECKLIST_VAULT_ERROR = "Beavis QoL: The vault window could not be opened right now.",
	CHECKLIST_EXPAND = "Expand tracker",
	CHECKLIST_EXPAND_HINT = "Shows the complete checklist again.",
	CHECKLIST_COLLAPSE = "Collapse tracker",
	CHECKLIST_COLLAPSE_HINT = "Hides the checklist and only leaves the header visible.",
	CHECKLIST_CLOSE = "Close tracker",
	CHECKLIST_CLOSE_HINT = "Hides the tracker window. You can show it again from the settings.",
	CHECKLIST_NEW_TASK = "New task",
	CHECKLIST_NEW_TASK_HINT = "Create a manual task directly in the tracker.",
	ADD_SHORT = "Add",
	ADD = "Add",
	FIX = "Fix",
	UNLOCK = "Unlock",
	CHECKLIST_TODO_WEEKLY_VAULT = "+10 or higher for the weekly vault",
	CHECKLIST_TODO_WEEKLY_RAID = "Raid for vault and BiS items",
	CHECKLIST_TODO_WEEKLY_PVP_QUESTS = "Weekly PvP quests",
	CHECKLIST_TODO_WEEKLY_HUNTS = "Nightmare prey hunts completed",
	CHECKLIST_TODO_WEEKLY_OPTIONAL_HUNTS = "Optional prey hunts completed",
	CHECKLIST_TODO_WEEKLY_SOIREE = "Soiree for weekly rewards",
	CHECKLIST_TODO_WEEKLY_OVERFLOW = "Overflow for weekly rewards",
	CHECKLIST_TODO_WEEKLY_STORMARION = "Stormarion assault for weekly rewards",
	CHECKLIST_TODO_WEEKLY_HARANDIR = "Harandir event for weekly rewards",
	CHECKLIST_TODO_WEEKLY_VOIDSTORM = "Voidstorm: 3 world quests for quartermaster reward",
	CHECKLIST_TODO_WEEKLY_DELVE_PROGRESS = "Weekly delve progress",
	CHECKLIST_TODO_WEEKLY_DELVE_HERO_MAP = "Weekly delve hero map",
	CHECKLIST_TODO_DAILY_DELVES = "4 bountiful delves for daily rewards",
	CHECKLIST_TODO_DAILY_WORLDQUESTS = "World quests for reputation and currencies",
	CHECKLIST_TODO_DAILY_M0 = "M0 world tour for extra loot",
	CHECKLIST_TODO_DAILY_HARANDIR = "Harandir daily quest for daily progress",
	CHECKLIST_TODO_WATCH_TIER = "4-piece set progress",
	CHECKLIST_TODO_WEEKLY_PROFESSION = "Farm max weekly profession points (%s)",
	STREAMER_PLANNER_ROLE = "Role",
	STREAMER_PLANNER_ROLE_AUTO = "Auto",
	STREAMER_PLANNER_SPEC_PROMPT_HINT_CLASS = "Choose class",
	STREAMER_PLANNER_SPEC_PROMPT_HINT_ROLE = "Choose role",
	STREAMER_PLANNER_SELF_ROLE_TITLE = "Choose your role",
	STREAMER_PLANNER_SELF_ROLE_HINT = "This decides which role your character is placed into in the dungeon planner. It is independent from your current spec.",
	STREAMER_PLANNER_APPLY = "Apply",
}
